// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/rpc/abox.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_rpc_abox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{0}
}

type StringMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMsg) Reset() {
	*x = StringMsg{}
	mi := &file_internal_rpc_abox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMsg) ProtoMessage() {}

func (x *StringMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMsg.ProtoReflect.Descriptor instead.
func (*StringMsg) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{1}
}

func (x *StringMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BoolMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolMsg) Reset() {
	*x = BoolMsg{}
	mi := &file_internal_rpc_abox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolMsg) ProtoMessage() {}

func (x *BoolMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolMsg.ProtoReflect.Descriptor instead.
func (*BoolMsg) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{2}
}

func (x *BoolMsg) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DomainReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainReq) Reset() {
	*x = DomainReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainReq) ProtoMessage() {}

func (x *DomainReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainReq.ProtoReflect.Descriptor instead.
func (*DomainReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{3}
}

func (x *DomainReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DomainList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainList) Reset() {
	*x = DomainList{}
	mi := &file_internal_rpc_abox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainList) ProtoMessage() {}

func (x *DomainList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainList.ProtoReflect.Descriptor instead.
func (*DomainList) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{4}
}

func (x *DomainList) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

// Egress-specific messages. These fields are the single source of truth for the
// permitted guest egress; the helper enforces exactly what is described here
// (after bounding/validating each field). See backend.EgressPolicy.
type EgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	DnsPort       int32                  `protobuf:"varint,2,opt,name=dns_port,json=dnsPort,proto3" json:"dns_port,omitempty"`                  // dnsfilter listen port (REDIRECT target + INPUT accept)
	HttpPort      int32                  `protobuf:"varint,3,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`               // httpfilter listen port (INPUT accept)
	GuestDnsPort  int32                  `protobuf:"varint,4,opt,name=guest_dns_port,json=guestDnsPort,proto3" json:"guest_dns_port,omitempty"` // guest-facing DNS port REDIRECTed to dns_port (normally 53)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressReq) Reset() {
	*x = EgressReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressReq) ProtoMessage() {}

func (x *EgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressReq.ProtoReflect.Descriptor instead.
func (*EgressReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{5}
}

func (x *EgressReq) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *EgressReq) GetDnsPort() int32 {
	if x != nil {
		return x.DnsPort
	}
	return 0
}

func (x *EgressReq) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

func (x *EgressReq) GetGuestDnsPort() int32 {
	if x != nil {
		return x.GuestDnsPort
	}
	return 0
}

// Pf-specific messages. The subnet is the single source of truth for what the
// instance's rules may match: the helper requires every source in the rules to
// be exactly this subnet (and every gateway to be its .1 host), which closes the
// cross-instance rule-injection hole.
type PfAnchorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"` // anchor-safe instance name (abox/<instance>)
	Subnet        string                 `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`     // deterministic per-instance /24 CIDR (e.g. 10.20.30.0/24)
	Rules         string                 `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`       // pf rules, each line bound token-for-token to subnet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfAnchorReq) Reset() {
	*x = PfAnchorReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfAnchorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfAnchorReq) ProtoMessage() {}

func (x *PfAnchorReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfAnchorReq.ProtoReflect.Descriptor instead.
func (*PfAnchorReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{6}
}

func (x *PfAnchorReq) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *PfAnchorReq) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *PfAnchorReq) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

type PfInstanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfInstanceReq) Reset() {
	*x = PfInstanceReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfInstanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfInstanceReq) ProtoMessage() {}

func (x *PfInstanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfInstanceReq.ProtoReflect.Descriptor instead.
func (*PfInstanceReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{7}
}

func (x *PfInstanceReq) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// EnsureStorageRootReq describes the per-user disk storage root to provision.
// The helper validates path equals <LibvirtImagesDir>/<peer-uid> (deriving the
// uid from the socket peer credentials, not from this field's contents), so it
// can only ever create the caller's own directory — never an arbitrary path.
type EnsureStorageRootReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // expected /var/lib/libvirt/images/abox/<uid>
	// regroup, when set, additionally walks the caller's OWN <uid> subtree after
	// provisioning the root and chgrps every entry to the resolved QEMU group and
	// fixes modes (dirs setgid, files group-readable). Used by `abox migrate`
	// after relocating files chowned them to the caller's primary group (which
	// loses the QEMU group). The walk root is ALWAYS the peer-uid's own subtree
	// (derived from the socket credentials, never from this field), never follows
	// symlinks out of it, and is otherwise a no-op.
	Regroup       bool `protobuf:"varint,2,opt,name=regroup,proto3" json:"regroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureStorageRootReq) Reset() {
	*x = EnsureStorageRootReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureStorageRootReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureStorageRootReq) ProtoMessage() {}

func (x *EnsureStorageRootReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureStorageRootReq.ProtoReflect.Descriptor instead.
func (*EnsureStorageRootReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{8}
}

func (x *EnsureStorageRootReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EnsureStorageRootReq) GetRegroup() bool {
	if x != nil {
		return x.Regroup
	}
	return false
}

// DNS-specific messages
type ModeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeReq) Reset() {
	*x = ModeReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeReq) ProtoMessage() {}

func (x *ModeReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeReq.ProtoReflect.Descriptor instead.
func (*ModeReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{9}
}

func (x *ModeReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subcommand    string                 `protobuf:"bytes,1,opt,name=subcommand,proto3" json:"subcommand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReq) Reset() {
	*x = ProfileReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReq) ProtoMessage() {}

func (x *ProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReq.ProtoReflect.Descriptor instead.
func (*ProfileReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{10}
}

func (x *ProfileReq) GetSubcommand() string {
	if x != nil {
		return x.Subcommand
	}
	return ""
}

type ProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResp) Reset() {
	*x = ProfileResp{}
	mi := &file_internal_rpc_abox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResp) ProtoMessage() {}

func (x *ProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResp.ProtoReflect.Descriptor instead.
func (*ProfileResp) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{11}
}

func (x *ProfileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProfileResp) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ProfileResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DNSStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Domains        int32                  `protobuf:"varint,2,opt,name=domains,proto3" json:"domains,omitempty"`
	TotalQueries   uint64                 `protobuf:"varint,3,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	AllowedQueries uint64                 `protobuf:"varint,4,opt,name=allowed_queries,json=allowedQueries,proto3" json:"allowed_queries,omitempty"`
	BlockedQueries uint64                 `protobuf:"varint,5,opt,name=blocked_queries,json=blockedQueries,proto3" json:"blocked_queries,omitempty"`
	CacheHits      uint64                 `protobuf:"varint,6,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	Uptime         string                 `protobuf:"bytes,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	DnsPort        int32                  `protobuf:"varint,8,opt,name=dns_port,json=dnsPort,proto3" json:"dns_port,omitempty"` // The actual port dnsfilter is listening on
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DNSStatus) Reset() {
	*x = DNSStatus{}
	mi := &file_internal_rpc_abox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSStatus) ProtoMessage() {}

func (x *DNSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSStatus.ProtoReflect.Descriptor instead.
func (*DNSStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{12}
}

func (x *DNSStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DNSStatus) GetDomains() int32 {
	if x != nil {
		return x.Domains
	}
	return 0
}

func (x *DNSStatus) GetTotalQueries() uint64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *DNSStatus) GetAllowedQueries() uint64 {
	if x != nil {
		return x.AllowedQueries
	}
	return 0
}

func (x *DNSStatus) GetBlockedQueries() uint64 {
	if x != nil {
		return x.BlockedQueries
	}
	return 0
}

func (x *DNSStatus) GetCacheHits() uint64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *DNSStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *DNSStatus) GetDnsPort() int32 {
	if x != nil {
		return x.DnsPort
	}
	return 0
}

type HTTPStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Mode            string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Domains         int32                  `protobuf:"varint,2,opt,name=domains,proto3" json:"domains,omitempty"`
	TotalRequests   uint64                 `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AllowedRequests uint64                 `protobuf:"varint,4,opt,name=allowed_requests,json=allowedRequests,proto3" json:"allowed_requests,omitempty"`
	BlockedRequests uint64                 `protobuf:"varint,5,opt,name=blocked_requests,json=blockedRequests,proto3" json:"blocked_requests,omitempty"`
	Uptime          string                 `protobuf:"bytes,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	HttpPort        int32                  `protobuf:"varint,7,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`          // The actual port httpfilter is listening on
	MitmEnabled     bool                   `protobuf:"varint,8,opt,name=mitm_enabled,json=mitmEnabled,proto3" json:"mitm_enabled,omitempty"` // Whether TLS MITM interception is active
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HTTPStatus) Reset() {
	*x = HTTPStatus{}
	mi := &file_internal_rpc_abox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPStatus) ProtoMessage() {}

func (x *HTTPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPStatus.ProtoReflect.Descriptor instead.
func (*HTTPStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{13}
}

func (x *HTTPStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HTTPStatus) GetDomains() int32 {
	if x != nil {
		return x.Domains
	}
	return 0
}

func (x *HTTPStatus) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *HTTPStatus) GetAllowedRequests() uint64 {
	if x != nil {
		return x.AllowedRequests
	}
	return 0
}

func (x *HTTPStatus) GetBlockedRequests() uint64 {
	if x != nil {
		return x.BlockedRequests
	}
	return 0
}

func (x *HTTPStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HTTPStatus) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

func (x *HTTPStatus) GetMitmEnabled() bool {
	if x != nil {
		return x.MitmEnabled
	}
	return false
}

// TLS key log messages
type KeyLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyLogReq) Reset() {
	*x = KeyLogReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLogReq) ProtoMessage() {}

func (x *KeyLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLogReq.ProtoReflect.Descriptor instead.
func (*KeyLogReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{14}
}

func (x *KeyLogReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Log level messages
type LogLevelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelReq) Reset() {
	*x = LogLevelReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelReq) ProtoMessage() {}

func (x *LogLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelReq.ProtoReflect.Descriptor instead.
func (*LogLevelReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{15}
}

func (x *LogLevelReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type LogLevelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelResp) Reset() {
	*x = LogLevelResp{}
	mi := &file_internal_rpc_abox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelResp) ProtoMessage() {}

func (x *LogLevelResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelResp.ProtoReflect.Descriptor instead.
func (*LogLevelResp) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{16}
}

func (x *LogLevelResp) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type MonitorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	EventsLogged  uint64                 `protobuf:"varint,2,opt,name=events_logged,json=eventsLogged,proto3" json:"events_logged,omitempty"`
	LogFile       string                 `protobuf:"bytes,3,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	LogSizeBytes  int64                  `protobuf:"varint,4,opt,name=log_size_bytes,json=logSizeBytes,proto3" json:"log_size_bytes,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorStatus) Reset() {
	*x = MonitorStatus{}
	mi := &file_internal_rpc_abox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorStatus) ProtoMessage() {}

func (x *MonitorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorStatus.ProtoReflect.Descriptor instead.
func (*MonitorStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{17}
}

func (x *MonitorStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *MonitorStatus) GetEventsLogged() uint64 {
	if x != nil {
		return x.EventsLogged
	}
	return 0
}

func (x *MonitorStatus) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *MonitorStatus) GetLogSizeBytes() int64 {
	if x != nil {
		return x.LogSizeBytes
	}
	return 0
}

func (x *MonitorStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

var File_internal_rpc_abox_proto protoreflect.FileDescriptor

const file_internal_rpc_abox_proto_rawDesc = "" +
	"\n" +
	"\x17internal/rpc/abox.proto\x12\x04abox\"\a\n" +
	"\x05Empty\"%\n" +
	"\tStringMsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x19\n" +
	"\aBoolMsg\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"#\n" +
	"\tDomainReq\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"&\n" +
	"\n" +
	"DomainList\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"\xa5\x01\n" +
	"\tEgressReq\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x19\n" +
	"\bdns_port\x18\x02 \x01(\x05R\adnsPort\x12\x1b\n" +
	"\thttp_port\x18\x03 \x01(\x05R\bhttpPort\x12$\n" +
	"\x0eguest_dns_port\x18\x04 \x01(\x05R\fguestDnsPortJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\n" +
	"allow_dhcpR\n" +
	"allow_icmp\"W\n" +
	"\vPfAnchorReq\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12\x14\n" +
	"\x05rules\x18\x03 \x01(\tR\x05rules\"+\n" +
	"\rPfInstanceReq\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"D\n" +
	"\x14EnsureStorageRootReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aregroup\x18\x02 \x01(\bR\aregroup\"\x1d\n" +
	"\aModeReq\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\",\n" +
	"\n" +
	"ProfileReq\x12\x1e\n" +
	"\n" +
	"subcommand\x18\x01 \x01(\tR\n" +
	"subcommand\"W\n" +
	"\vProfileResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x82\x02\n" +
	"\tDNSStatus\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x18\n" +
	"\adomains\x18\x02 \x01(\x05R\adomains\x12#\n" +
	"\rtotal_queries\x18\x03 \x01(\x04R\ftotalQueries\x12'\n" +
	"\x0fallowed_queries\x18\x04 \x01(\x04R\x0eallowedQueries\x12'\n" +
	"\x0fblocked_queries\x18\x05 \x01(\x04R\x0eblockedQueries\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x06 \x01(\x04R\tcacheHits\x12\x16\n" +
	"\x06uptime\x18\a \x01(\tR\x06uptime\x12\x19\n" +
	"\bdns_port\x18\b \x01(\x05R\adnsPort\"\x8f\x02\n" +
	"\n" +
	"HTTPStatus\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x18\n" +
	"\adomains\x18\x02 \x01(\x05R\adomains\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x04R\rtotalRequests\x12)\n" +
	"\x10allowed_requests\x18\x04 \x01(\x04R\x0fallowedRequests\x12)\n" +
	"\x10blocked_requests\x18\x05 \x01(\x04R\x0fblockedRequests\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\tR\x06uptime\x12\x1b\n" +
	"\thttp_port\x18\a \x01(\x05R\bhttpPort\x12!\n" +
	"\fmitm_enabled\x18\b \x01(\bR\vmitmEnabled\"\x1f\n" +
	"\tKeyLogReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\vLogLevelReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"$\n" +
	"\fLogLevelResp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"\xa7\x01\n" +
	"\rMonitorStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12#\n" +
	"\revents_logged\x18\x02 \x01(\x04R\feventsLogged\x12\x19\n" +
	"\blog_file\x18\x03 \x01(\tR\alogFile\x12$\n" +
	"\x0elog_size_bytes\x18\x04 \x01(\x03R\flogSizeBytes\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime2\x8b\x02\n" +
	"\x06Egress\x12$\n" +
	"\x04Ping\x12\v.abox.Empty\x1a\x0f.abox.StringMsg\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty\x12<\n" +
	"\x11EnsureStorageRoot\x12\x1a.abox.EnsureStorageRootReq\x1a\v.abox.Empty\x12%\n" +
	"\x05Apply\x12\x0f.abox.EgressReq\x1a\v.abox.Empty\x12&\n" +
	"\x06Remove\x12\x0f.abox.EgressReq\x1a\v.abox.Empty\x12(\n" +
	"\x06Verify\x12\x0f.abox.EgressReq\x1a\r.abox.BoolMsg2\xff\x01\n" +
	"\x02Pf\x12$\n" +
	"\x04Ping\x12\v.abox.Empty\x1a\x0f.abox.StringMsg\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty\x12\"\n" +
	"\x06Enable\x12\v.abox.Empty\x1a\v.abox.Empty\x12,\n" +
	"\n" +
	"LoadAnchor\x12\x11.abox.PfAnchorReq\x1a\v.abox.Empty\x12/\n" +
	"\vFlushAnchor\x12\x13.abox.PfInstanceReq\x1a\v.abox.Empty\x12*\n" +
	"\x0eTeardownConfig\x12\v.abox.Empty\x1a\v.abox.Empty2\x97\x02\n" +
	"\tDNSFilter\x12&\n" +
	"\x06Status\x12\v.abox.Empty\x1a\x0f.abox.DNSStatus\x12)\n" +
	"\aSetMode\x12\r.abox.ModeReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\aProfile\x12\x10.abox.ProfileReq\x1a\x11.abox.ProfileResp\x121\n" +
	"\vSetLogLevel\x12\x11.abox.LogLevelReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\vGetLogLevel\x12\v.abox.Empty\x1a\x12.abox.LogLevelResp\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty2\xaf\x01\n" +
	"\tAllowlist\x12'\n" +
	"\x03Add\x12\x0f.abox.DomainReq\x1a\x0f.abox.StringMsg\x12*\n" +
	"\x06Remove\x12\x0f.abox.DomainReq\x1a\x0f.abox.StringMsg\x12%\n" +
	"\x04List\x12\v.abox.Empty\x1a\x10.abox.DomainList\x12&\n" +
	"\x06Reload\x12\v.abox.Empty\x1a\x0f.abox.StringMsg2\xee\x02\n" +
	"\n" +
	"HTTPFilter\x12'\n" +
	"\x06Status\x12\v.abox.Empty\x1a\x10.abox.HTTPStatus\x12)\n" +
	"\aSetMode\x12\r.abox.ModeReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\aProfile\x12\x10.abox.ProfileReq\x1a\x11.abox.ProfileResp\x121\n" +
	"\vSetLogLevel\x12\x11.abox.LogLevelReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\vGetLogLevel\x12\v.abox.Empty\x1a\x12.abox.LogLevelResp\x12+\n" +
	"\vStartKeyLog\x12\x0f.abox.KeyLogReq\x1a\v.abox.Empty\x12&\n" +
	"\n" +
	"StopKeyLog\x12\v.abox.Empty\x1a\v.abox.Empty\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty2[\n" +
	"\aMonitor\x12*\n" +
	"\x06Status\x12\v.abox.Empty\x1a\x13.abox.MonitorStatus\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.EmptyB)Z'github.com/sandialabs/abox/internal/rpcb\x06proto3"

var (
	file_internal_rpc_abox_proto_rawDescOnce sync.Once
	file_internal_rpc_abox_proto_rawDescData []byte
)

func file_internal_rpc_abox_proto_rawDescGZIP() []byte {
	file_internal_rpc_abox_proto_rawDescOnce.Do(func() {
		file_internal_rpc_abox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_abox_proto_rawDesc), len(file_internal_rpc_abox_proto_rawDesc)))
	})
	return file_internal_rpc_abox_proto_rawDescData
}

var file_internal_rpc_abox_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_rpc_abox_proto_goTypes = []any{
	(*Empty)(nil),                // 0: abox.Empty
	(*StringMsg)(nil),            // 1: abox.StringMsg
	(*BoolMsg)(nil),              // 2: abox.BoolMsg
	(*DomainReq)(nil),            // 3: abox.DomainReq
	(*DomainList)(nil),           // 4: abox.DomainList
	(*EgressReq)(nil),            // 5: abox.EgressReq
	(*PfAnchorReq)(nil),          // 6: abox.PfAnchorReq
	(*PfInstanceReq)(nil),        // 7: abox.PfInstanceReq
	(*EnsureStorageRootReq)(nil), // 8: abox.EnsureStorageRootReq
	(*ModeReq)(nil),              // 9: abox.ModeReq
	(*ProfileReq)(nil),           // 10: abox.ProfileReq
	(*ProfileResp)(nil),          // 11: abox.ProfileResp
	(*DNSStatus)(nil),            // 12: abox.DNSStatus
	(*HTTPStatus)(nil),           // 13: abox.HTTPStatus
	(*KeyLogReq)(nil),            // 14: abox.KeyLogReq
	(*LogLevelReq)(nil),          // 15: abox.LogLevelReq
	(*LogLevelResp)(nil),         // 16: abox.LogLevelResp
	(*MonitorStatus)(nil),        // 17: abox.MonitorStatus
}
var file_internal_rpc_abox_proto_depIdxs = []int32{
	0,  // 0: abox.Egress.Ping:input_type -> abox.Empty
	0,  // 1: abox.Egress.Shutdown:input_type -> abox.Empty
	8,  // 2: abox.Egress.EnsureStorageRoot:input_type -> abox.EnsureStorageRootReq
	5,  // 3: abox.Egress.Apply:input_type -> abox.EgressReq
	5,  // 4: abox.Egress.Remove:input_type -> abox.EgressReq
	5,  // 5: abox.Egress.Verify:input_type -> abox.EgressReq
	0,  // 6: abox.Pf.Ping:input_type -> abox.Empty
	0,  // 7: abox.Pf.Shutdown:input_type -> abox.Empty
	0,  // 8: abox.Pf.Enable:input_type -> abox.Empty
	6,  // 9: abox.Pf.LoadAnchor:input_type -> abox.PfAnchorReq
	7,  // 10: abox.Pf.FlushAnchor:input_type -> abox.PfInstanceReq
	0,  // 11: abox.Pf.TeardownConfig:input_type -> abox.Empty
	0,  // 12: abox.DNSFilter.Status:input_type -> abox.Empty
	9,  // 13: abox.DNSFilter.SetMode:input_type -> abox.ModeReq
	10, // 14: abox.DNSFilter.Profile:input_type -> abox.ProfileReq
	15, // 15: abox.DNSFilter.SetLogLevel:input_type -> abox.LogLevelReq
	0,  // 16: abox.DNSFilter.GetLogLevel:input_type -> abox.Empty
	0,  // 17: abox.DNSFilter.Shutdown:input_type -> abox.Empty
	3,  // 18: abox.Allowlist.Add:input_type -> abox.DomainReq
	3,  // 19: abox.Allowlist.Remove:input_type -> abox.DomainReq
	0,  // 20: abox.Allowlist.List:input_type -> abox.Empty
	0,  // 21: abox.Allowlist.Reload:input_type -> abox.Empty
	0,  // 22: abox.HTTPFilter.Status:input_type -> abox.Empty
	9,  // 23: abox.HTTPFilter.SetMode:input_type -> abox.ModeReq
	10, // 24: abox.HTTPFilter.Profile:input_type -> abox.ProfileReq
	15, // 25: abox.HTTPFilter.SetLogLevel:input_type -> abox.LogLevelReq
	0,  // 26: abox.HTTPFilter.GetLogLevel:input_type -> abox.Empty
	14, // 27: abox.HTTPFilter.StartKeyLog:input_type -> abox.KeyLogReq
	0,  // 28: abox.HTTPFilter.StopKeyLog:input_type -> abox.Empty
	0,  // 29: abox.HTTPFilter.Shutdown:input_type -> abox.Empty
	0,  // 30: abox.Monitor.Status:input_type -> abox.Empty
	0,  // 31: abox.Monitor.Shutdown:input_type -> abox.Empty
	1,  // 32: abox.Egress.Ping:output_type -> abox.StringMsg
	0,  // 33: abox.Egress.Shutdown:output_type -> abox.Empty
	0,  // 34: abox.Egress.EnsureStorageRoot:output_type -> abox.Empty
	0,  // 35: abox.Egress.Apply:output_type -> abox.Empty
	0,  // 36: abox.Egress.Remove:output_type -> abox.Empty
	2,  // 37: abox.Egress.Verify:output_type -> abox.BoolMsg
	1,  // 38: abox.Pf.Ping:output_type -> abox.StringMsg
	0,  // 39: abox.Pf.Shutdown:output_type -> abox.Empty
	0,  // 40: abox.Pf.Enable:output_type -> abox.Empty
	0,  // 41: abox.Pf.LoadAnchor:output_type -> abox.Empty
	0,  // 42: abox.Pf.FlushAnchor:output_type -> abox.Empty
	0,  // 43: abox.Pf.TeardownConfig:output_type -> abox.Empty
	12, // 44: abox.DNSFilter.Status:output_type -> abox.DNSStatus
	1,  // 45: abox.DNSFilter.SetMode:output_type -> abox.StringMsg
	11, // 46: abox.DNSFilter.Profile:output_type -> abox.ProfileResp
	1,  // 47: abox.DNSFilter.SetLogLevel:output_type -> abox.StringMsg
	16, // 48: abox.DNSFilter.GetLogLevel:output_type -> abox.LogLevelResp
	0,  // 49: abox.DNSFilter.Shutdown:output_type -> abox.Empty
	1,  // 50: abox.Allowlist.Add:output_type -> abox.StringMsg
	1,  // 51: abox.Allowlist.Remove:output_type -> abox.StringMsg
	4,  // 52: abox.Allowlist.List:output_type -> abox.DomainList
	1,  // 53: abox.Allowlist.Reload:output_type -> abox.StringMsg
	13, // 54: abox.HTTPFilter.Status:output_type -> abox.HTTPStatus
	1,  // 55: abox.HTTPFilter.SetMode:output_type -> abox.StringMsg
	11, // 56: abox.HTTPFilter.Profile:output_type -> abox.ProfileResp
	1,  // 57: abox.HTTPFilter.SetLogLevel:output_type -> abox.StringMsg
	16, // 58: abox.HTTPFilter.GetLogLevel:output_type -> abox.LogLevelResp
	0,  // 59: abox.HTTPFilter.StartKeyLog:output_type -> abox.Empty
	0,  // 60: abox.HTTPFilter.StopKeyLog:output_type -> abox.Empty
	0,  // 61: abox.HTTPFilter.Shutdown:output_type -> abox.Empty
	17, // 62: abox.Monitor.Status:output_type -> abox.MonitorStatus
	0,  // 63: abox.Monitor.Shutdown:output_type -> abox.Empty
	32, // [32:64] is the sub-list for method output_type
	0,  // [0:32] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_rpc_abox_proto_init() }
func file_internal_rpc_abox_proto_init() {
	if File_internal_rpc_abox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_abox_proto_rawDesc), len(file_internal_rpc_abox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_internal_rpc_abox_proto_goTypes,
		DependencyIndexes: file_internal_rpc_abox_proto_depIdxs,
		MessageInfos:      file_internal_rpc_abox_proto_msgTypes,
	}.Build()
	File_internal_rpc_abox_proto = out.File
	file_internal_rpc_abox_proto_goTypes = nil
	file_internal_rpc_abox_proto_depIdxs = nil
}
