// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/rpc/abox.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Egress_Ping_FullMethodName              = "/abox.Egress/Ping"
	Egress_Shutdown_FullMethodName          = "/abox.Egress/Shutdown"
	Egress_EnsureStorageRoot_FullMethodName = "/abox.Egress/EnsureStorageRoot"
	Egress_Apply_FullMethodName             = "/abox.Egress/Apply"
	Egress_Remove_FullMethodName            = "/abox.Egress/Remove"
	Egress_Verify_FullMethodName            = "/abox.Egress/Verify"
)

// EgressClient is the client API for Egress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Egress Helper Service - runs privileged (CAP_NET_ADMIN) for network egress
// enforcement. Per-instance disk operations run unprivileged; the one privileged
// storage step (provisioning the per-user disk root) is exposed via
// EnsureStorageRoot.
type EgressClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// EnsureStorageRoot idempotently provisions the caller's per-user disk storage
	// root under /var/lib/libvirt/images/abox: it creates the shared parent (once,
	// root-owned) and the per-user subdir owned by the caller and setgid to the
	// QEMU runtime group, so images created there inherit that group and are
	// readable by the VM process without ACLs or any $HOME traversal. The helper
	// derives the caller from the socket peer credentials and creates only
	// <parent>/<caller-uid>, so a client can never provision another user's dir.
	EnsureStorageRoot(ctx context.Context, in *EnsureStorageRootReq, opts ...grpc.CallOption) (*Empty, error)
	// Apply installs the host-side egress enforcement for a bridge: a NAT
	// PREROUTING REDIRECT of guest DNS (the guest-facing DNS port) to the
	// dnsfilter port, plus INPUT ACCEPT rules for the dnsfilter and httpfilter
	// ports (and optionally DHCP/ICMP). Idempotent (stale rules for the bridge
	// are flushed first). The permitted set is driven entirely by the request.
	Apply(ctx context.Context, in *EgressReq, opts ...grpc.CallOption) (*Empty, error)
	// Remove flushes the host-side egress rules for a bridge (idempotent). The
	// request's ports scope the flush to abox's own rules.
	Remove(ctx context.Context, in *EgressReq, opts ...grpc.CallOption) (*Empty, error)
	// Verify reports whether the complete host-side egress rule set described by
	// the request is currently in force (drift detection for status/doctor).
	Verify(ctx context.Context, in *EgressReq, opts ...grpc.CallOption) (*BoolMsg, error)
}

type egressClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressClient(cc grpc.ClientConnInterface) EgressClient {
	return &egressClient{cc}
}

func (c *egressClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Egress_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Egress_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressClient) EnsureStorageRoot(ctx context.Context, in *EnsureStorageRootReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Egress_EnsureStorageRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressClient) Apply(ctx context.Context, in *EgressReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Egress_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressClient) Remove(ctx context.Context, in *EgressReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Egress_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressClient) Verify(ctx context.Context, in *EgressReq, opts ...grpc.CallOption) (*BoolMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolMsg)
	err := c.cc.Invoke(ctx, Egress_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressServer is the server API for Egress service.
// All implementations must embed UnimplementedEgressServer
// for forward compatibility.
//
// Egress Helper Service - runs privileged (CAP_NET_ADMIN) for network egress
// enforcement. Per-instance disk operations run unprivileged; the one privileged
// storage step (provisioning the per-user disk root) is exposed via
// EnsureStorageRoot.
type EgressServer interface {
	Ping(context.Context, *Empty) (*StringMsg, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	// EnsureStorageRoot idempotently provisions the caller's per-user disk storage
	// root under /var/lib/libvirt/images/abox: it creates the shared parent (once,
	// root-owned) and the per-user subdir owned by the caller and setgid to the
	// QEMU runtime group, so images created there inherit that group and are
	// readable by the VM process without ACLs or any $HOME traversal. The helper
	// derives the caller from the socket peer credentials and creates only
	// <parent>/<caller-uid>, so a client can never provision another user's dir.
	EnsureStorageRoot(context.Context, *EnsureStorageRootReq) (*Empty, error)
	// Apply installs the host-side egress enforcement for a bridge: a NAT
	// PREROUTING REDIRECT of guest DNS (the guest-facing DNS port) to the
	// dnsfilter port, plus INPUT ACCEPT rules for the dnsfilter and httpfilter
	// ports (and optionally DHCP/ICMP). Idempotent (stale rules for the bridge
	// are flushed first). The permitted set is driven entirely by the request.
	Apply(context.Context, *EgressReq) (*Empty, error)
	// Remove flushes the host-side egress rules for a bridge (idempotent). The
	// request's ports scope the flush to abox's own rules.
	Remove(context.Context, *EgressReq) (*Empty, error)
	// Verify reports whether the complete host-side egress rule set described by
	// the request is currently in force (drift detection for status/doctor).
	Verify(context.Context, *EgressReq) (*BoolMsg, error)
	mustEmbedUnimplementedEgressServer()
}

// UnimplementedEgressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressServer struct{}

func (UnimplementedEgressServer) Ping(context.Context, *Empty) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEgressServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedEgressServer) EnsureStorageRoot(context.Context, *EnsureStorageRootReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureStorageRoot not implemented")
}
func (UnimplementedEgressServer) Apply(context.Context, *EgressReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedEgressServer) Remove(context.Context, *EgressReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedEgressServer) Verify(context.Context, *EgressReq) (*BoolMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedEgressServer) mustEmbedUnimplementedEgressServer() {}
func (UnimplementedEgressServer) testEmbeddedByValue()                {}

// UnsafeEgressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressServer will
// result in compilation errors.
type UnsafeEgressServer interface {
	mustEmbedUnimplementedEgressServer()
}

func RegisterEgressServer(s grpc.ServiceRegistrar, srv EgressServer) {
	// If the following call panics, it indicates UnimplementedEgressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Egress_ServiceDesc, srv)
}

func _Egress_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egress_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egress_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egress_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egress_EnsureStorageRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureStorageRootReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).EnsureStorageRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egress_EnsureStorageRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).EnsureStorageRoot(ctx, req.(*EnsureStorageRootReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egress_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egress_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Apply(ctx, req.(*EgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egress_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egress_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Remove(ctx, req.(*EgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egress_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egress_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Verify(ctx, req.(*EgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Egress_ServiceDesc is the grpc.ServiceDesc for Egress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Egress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Egress",
	HandlerType: (*EgressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Egress_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Egress_Shutdown_Handler,
		},
		{
			MethodName: "EnsureStorageRoot",
			Handler:    _Egress_EnsureStorageRoot_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Egress_Apply_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Egress_Remove_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Egress_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	Pf_Ping_FullMethodName           = "/abox.Pf/Ping"
	Pf_Shutdown_FullMethodName       = "/abox.Pf/Shutdown"
	Pf_Enable_FullMethodName         = "/abox.Pf/Enable"
	Pf_LoadAnchor_FullMethodName     = "/abox.Pf/LoadAnchor"
	Pf_FlushAnchor_FullMethodName    = "/abox.Pf/FlushAnchor"
	Pf_TeardownConfig_FullMethodName = "/abox.Pf/TeardownConfig"
)

// PfClient is the client API for Pf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Pf Service - runs privileged (root via sudo) for macOS pfctl egress
// enforcement. Per-instance rules live in the abox/<instance> anchor and key on
// the instance's deterministic /24 subnet (known at Define time, before the VM's
// DHCP IP is assigned). Disk/storage operations run unprivileged and are not
// exposed here.
type PfClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Enable turns on pf (if needed) and wires the abox/* anchor references into
	// /etc/pf.conf so the kernel descends into the per-instance sub-anchors.
	// Idempotent.
	Enable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// LoadAnchor validates the request (anchor-safe instance name, /24 subnet, and
	// rules bound token-for-token to that subnet) and loads the rules into the
	// abox/<instance> anchor.
	LoadAnchor(ctx context.Context, in *PfAnchorReq, opts ...grpc.CallOption) (*Empty, error)
	// FlushAnchor removes the per-instance rules from abox/<instance> (idempotent).
	FlushAnchor(ctx context.Context, in *PfInstanceReq, opts ...grpc.CallOption) (*Empty, error)
	// TeardownConfig removes the abox/* anchor references from /etc/pf.conf.
	TeardownConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type pfClient struct {
	cc grpc.ClientConnInterface
}

func NewPfClient(cc grpc.ClientConnInterface) PfClient {
	return &pfClient{cc}
}

func (c *pfClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Pf_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pfClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pf_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pfClient) Enable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pf_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pfClient) LoadAnchor(ctx context.Context, in *PfAnchorReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pf_LoadAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pfClient) FlushAnchor(ctx context.Context, in *PfInstanceReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pf_FlushAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pfClient) TeardownConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pf_TeardownConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PfServer is the server API for Pf service.
// All implementations must embed UnimplementedPfServer
// for forward compatibility.
//
// Pf Service - runs privileged (root via sudo) for macOS pfctl egress
// enforcement. Per-instance rules live in the abox/<instance> anchor and key on
// the instance's deterministic /24 subnet (known at Define time, before the VM's
// DHCP IP is assigned). Disk/storage operations run unprivileged and are not
// exposed here.
type PfServer interface {
	Ping(context.Context, *Empty) (*StringMsg, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	// Enable turns on pf (if needed) and wires the abox/* anchor references into
	// /etc/pf.conf so the kernel descends into the per-instance sub-anchors.
	// Idempotent.
	Enable(context.Context, *Empty) (*Empty, error)
	// LoadAnchor validates the request (anchor-safe instance name, /24 subnet, and
	// rules bound token-for-token to that subnet) and loads the rules into the
	// abox/<instance> anchor.
	LoadAnchor(context.Context, *PfAnchorReq) (*Empty, error)
	// FlushAnchor removes the per-instance rules from abox/<instance> (idempotent).
	FlushAnchor(context.Context, *PfInstanceReq) (*Empty, error)
	// TeardownConfig removes the abox/* anchor references from /etc/pf.conf.
	TeardownConfig(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedPfServer()
}

// UnimplementedPfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPfServer struct{}

func (UnimplementedPfServer) Ping(context.Context, *Empty) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPfServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPfServer) Enable(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedPfServer) LoadAnchor(context.Context, *PfAnchorReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadAnchor not implemented")
}
func (UnimplementedPfServer) FlushAnchor(context.Context, *PfInstanceReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushAnchor not implemented")
}
func (UnimplementedPfServer) TeardownConfig(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TeardownConfig not implemented")
}
func (UnimplementedPfServer) mustEmbedUnimplementedPfServer() {}
func (UnimplementedPfServer) testEmbeddedByValue()            {}

// UnsafePfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PfServer will
// result in compilation errors.
type UnsafePfServer interface {
	mustEmbedUnimplementedPfServer()
}

func RegisterPfServer(s grpc.ServiceRegistrar, srv PfServer) {
	// If the following call panics, it indicates UnimplementedPfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pf_ServiceDesc, srv)
}

func _Pf_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PfServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pf_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PfServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pf_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PfServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pf_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PfServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pf_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PfServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pf_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PfServer).Enable(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pf_LoadAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PfAnchorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PfServer).LoadAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pf_LoadAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PfServer).LoadAnchor(ctx, req.(*PfAnchorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pf_FlushAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PfInstanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PfServer).FlushAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pf_FlushAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PfServer).FlushAnchor(ctx, req.(*PfInstanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pf_TeardownConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PfServer).TeardownConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pf_TeardownConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PfServer).TeardownConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Pf_ServiceDesc is the grpc.ServiceDesc for Pf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Pf",
	HandlerType: (*PfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pf_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Pf_Shutdown_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _Pf_Enable_Handler,
		},
		{
			MethodName: "LoadAnchor",
			Handler:    _Pf_LoadAnchor_Handler,
		},
		{
			MethodName: "FlushAnchor",
			Handler:    _Pf_FlushAnchor_Handler,
		},
		{
			MethodName: "TeardownConfig",
			Handler:    _Pf_TeardownConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	DNSFilter_Status_FullMethodName      = "/abox.DNSFilter/Status"
	DNSFilter_SetMode_FullMethodName     = "/abox.DNSFilter/SetMode"
	DNSFilter_Profile_FullMethodName     = "/abox.DNSFilter/Profile"
	DNSFilter_SetLogLevel_FullMethodName = "/abox.DNSFilter/SetLogLevel"
	DNSFilter_GetLogLevel_FullMethodName = "/abox.DNSFilter/GetLogLevel"
	DNSFilter_Shutdown_FullMethodName    = "/abox.DNSFilter/Shutdown"
)

// DNSFilterClient is the client API for DNSFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DNS Filter Service - manages DNS filtering
type DNSFilterClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DNSStatus, error)
	SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error)
	Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error)
	SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error)
	GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type dNSFilterClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSFilterClient(cc grpc.ClientConnInterface) DNSFilterClient {
	return &dNSFilterClient{cc}
}

func (c *dNSFilterClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DNSStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSStatus)
	err := c.cc.Invoke(ctx, DNSFilter_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, DNSFilter_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResp)
	err := c.cc.Invoke(ctx, DNSFilter_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, DNSFilter_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelResp)
	err := c.cc.Invoke(ctx, DNSFilter_GetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DNSFilter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSFilterServer is the server API for DNSFilter service.
// All implementations must embed UnimplementedDNSFilterServer
// for forward compatibility.
//
// DNS Filter Service - manages DNS filtering
type DNSFilterServer interface {
	Status(context.Context, *Empty) (*DNSStatus, error)
	SetMode(context.Context, *ModeReq) (*StringMsg, error)
	Profile(context.Context, *ProfileReq) (*ProfileResp, error)
	SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error)
	GetLogLevel(context.Context, *Empty) (*LogLevelResp, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedDNSFilterServer()
}

// UnimplementedDNSFilterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSFilterServer struct{}

func (UnimplementedDNSFilterServer) Status(context.Context, *Empty) (*DNSStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDNSFilterServer) SetMode(context.Context, *ModeReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedDNSFilterServer) Profile(context.Context, *ProfileReq) (*ProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedDNSFilterServer) SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedDNSFilterServer) GetLogLevel(context.Context, *Empty) (*LogLevelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogLevel not implemented")
}
func (UnimplementedDNSFilterServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDNSFilterServer) mustEmbedUnimplementedDNSFilterServer() {}
func (UnimplementedDNSFilterServer) testEmbeddedByValue()                   {}

// UnsafeDNSFilterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSFilterServer will
// result in compilation errors.
type UnsafeDNSFilterServer interface {
	mustEmbedUnimplementedDNSFilterServer()
}

func RegisterDNSFilterServer(s grpc.ServiceRegistrar, srv DNSFilterServer) {
	// If the following call panics, it indicates UnimplementedDNSFilterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSFilter_ServiceDesc, srv)
}

func _DNSFilter_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).SetMode(ctx, req.(*ModeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).Profile(ctx, req.(*ProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).SetLogLevel(ctx, req.(*LogLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_GetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).GetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_GetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).GetLogLevel(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSFilter_ServiceDesc is the grpc.ServiceDesc for DNSFilter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSFilter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.DNSFilter",
	HandlerType: (*DNSFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _DNSFilter_Status_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _DNSFilter_SetMode_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _DNSFilter_Profile_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _DNSFilter_SetLogLevel_Handler,
		},
		{
			MethodName: "GetLogLevel",
			Handler:    _DNSFilter_GetLogLevel_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DNSFilter_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	Allowlist_Add_FullMethodName    = "/abox.Allowlist/Add"
	Allowlist_Remove_FullMethodName = "/abox.Allowlist/Remove"
	Allowlist_List_FullMethodName   = "/abox.Allowlist/List"
	Allowlist_Reload_FullMethodName = "/abox.Allowlist/Reload"
)

// AllowlistClient is the client API for Allowlist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Allowlist Service - manages shared domain allowlist
// Used by both DNS and HTTP filters
type AllowlistClient interface {
	Add(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error)
	Remove(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainList, error)
	Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error)
}

type allowlistClient struct {
	cc grpc.ClientConnInterface
}

func NewAllowlistClient(cc grpc.ClientConnInterface) AllowlistClient {
	return &allowlistClient{cc}
}

func (c *allowlistClient) Add(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Allowlist_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *allowlistClient) Remove(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Allowlist_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *allowlistClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainList)
	err := c.cc.Invoke(ctx, Allowlist_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *allowlistClient) Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Allowlist_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllowlistServer is the server API for Allowlist service.
// All implementations must embed UnimplementedAllowlistServer
// for forward compatibility.
//
// Allowlist Service - manages shared domain allowlist
// Used by both DNS and HTTP filters
type AllowlistServer interface {
	Add(context.Context, *DomainReq) (*StringMsg, error)
	Remove(context.Context, *DomainReq) (*StringMsg, error)
	List(context.Context, *Empty) (*DomainList, error)
	Reload(context.Context, *Empty) (*StringMsg, error)
	mustEmbedUnimplementedAllowlistServer()
}

// UnimplementedAllowlistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAllowlistServer struct{}

func (UnimplementedAllowlistServer) Add(context.Context, *DomainReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAllowlistServer) Remove(context.Context, *DomainReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedAllowlistServer) List(context.Context, *Empty) (*DomainList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAllowlistServer) Reload(context.Context, *Empty) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedAllowlistServer) mustEmbedUnimplementedAllowlistServer() {}
func (UnimplementedAllowlistServer) testEmbeddedByValue()                   {}

// UnsafeAllowlistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AllowlistServer will
// result in compilation errors.
type UnsafeAllowlistServer interface {
	mustEmbedUnimplementedAllowlistServer()
}

func RegisterAllowlistServer(s grpc.ServiceRegistrar, srv AllowlistServer) {
	// If the following call panics, it indicates UnimplementedAllowlistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Allowlist_ServiceDesc, srv)
}

func _Allowlist_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).Add(ctx, req.(*DomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Allowlist_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).Remove(ctx, req.(*DomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Allowlist_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Allowlist_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).Reload(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Allowlist_ServiceDesc is the grpc.ServiceDesc for Allowlist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Allowlist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Allowlist",
	HandlerType: (*AllowlistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Allowlist_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Allowlist_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Allowlist_List_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _Allowlist_Reload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	HTTPFilter_Status_FullMethodName      = "/abox.HTTPFilter/Status"
	HTTPFilter_SetMode_FullMethodName     = "/abox.HTTPFilter/SetMode"
	HTTPFilter_Profile_FullMethodName     = "/abox.HTTPFilter/Profile"
	HTTPFilter_SetLogLevel_FullMethodName = "/abox.HTTPFilter/SetLogLevel"
	HTTPFilter_GetLogLevel_FullMethodName = "/abox.HTTPFilter/GetLogLevel"
	HTTPFilter_StartKeyLog_FullMethodName = "/abox.HTTPFilter/StartKeyLog"
	HTTPFilter_StopKeyLog_FullMethodName  = "/abox.HTTPFilter/StopKeyLog"
	HTTPFilter_Shutdown_FullMethodName    = "/abox.HTTPFilter/Shutdown"
)

// HTTPFilterClient is the client API for HTTPFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HTTP Filter Service - manages HTTP proxy filtering
type HTTPFilterClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HTTPStatus, error)
	SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error)
	Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error)
	SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error)
	GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error)
	StartKeyLog(ctx context.Context, in *KeyLogReq, opts ...grpc.CallOption) (*Empty, error)
	StopKeyLog(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type hTTPFilterClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPFilterClient(cc grpc.ClientConnInterface) HTTPFilterClient {
	return &hTTPFilterClient{cc}
}

func (c *hTTPFilterClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HTTPStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPStatus)
	err := c.cc.Invoke(ctx, HTTPFilter_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, HTTPFilter_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResp)
	err := c.cc.Invoke(ctx, HTTPFilter_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, HTTPFilter_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelResp)
	err := c.cc.Invoke(ctx, HTTPFilter_GetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) StartKeyLog(ctx context.Context, in *KeyLogReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HTTPFilter_StartKeyLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) StopKeyLog(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HTTPFilter_StopKeyLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HTTPFilter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPFilterServer is the server API for HTTPFilter service.
// All implementations must embed UnimplementedHTTPFilterServer
// for forward compatibility.
//
// HTTP Filter Service - manages HTTP proxy filtering
type HTTPFilterServer interface {
	Status(context.Context, *Empty) (*HTTPStatus, error)
	SetMode(context.Context, *ModeReq) (*StringMsg, error)
	Profile(context.Context, *ProfileReq) (*ProfileResp, error)
	SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error)
	GetLogLevel(context.Context, *Empty) (*LogLevelResp, error)
	StartKeyLog(context.Context, *KeyLogReq) (*Empty, error)
	StopKeyLog(context.Context, *Empty) (*Empty, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedHTTPFilterServer()
}

// UnimplementedHTTPFilterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPFilterServer struct{}

func (UnimplementedHTTPFilterServer) Status(context.Context, *Empty) (*HTTPStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHTTPFilterServer) SetMode(context.Context, *ModeReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedHTTPFilterServer) Profile(context.Context, *ProfileReq) (*ProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedHTTPFilterServer) SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedHTTPFilterServer) GetLogLevel(context.Context, *Empty) (*LogLevelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogLevel not implemented")
}
func (UnimplementedHTTPFilterServer) StartKeyLog(context.Context, *KeyLogReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartKeyLog not implemented")
}
func (UnimplementedHTTPFilterServer) StopKeyLog(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopKeyLog not implemented")
}
func (UnimplementedHTTPFilterServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedHTTPFilterServer) mustEmbedUnimplementedHTTPFilterServer() {}
func (UnimplementedHTTPFilterServer) testEmbeddedByValue()                    {}

// UnsafeHTTPFilterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPFilterServer will
// result in compilation errors.
type UnsafeHTTPFilterServer interface {
	mustEmbedUnimplementedHTTPFilterServer()
}

func RegisterHTTPFilterServer(s grpc.ServiceRegistrar, srv HTTPFilterServer) {
	// If the following call panics, it indicates UnimplementedHTTPFilterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPFilter_ServiceDesc, srv)
}

func _HTTPFilter_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).SetMode(ctx, req.(*ModeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).Profile(ctx, req.(*ProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).SetLogLevel(ctx, req.(*LogLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_GetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).GetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_GetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).GetLogLevel(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_StartKeyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).StartKeyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_StartKeyLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).StartKeyLog(ctx, req.(*KeyLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_StopKeyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).StopKeyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_StopKeyLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).StopKeyLog(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPFilter_ServiceDesc is the grpc.ServiceDesc for HTTPFilter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPFilter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.HTTPFilter",
	HandlerType: (*HTTPFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HTTPFilter_Status_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _HTTPFilter_SetMode_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _HTTPFilter_Profile_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _HTTPFilter_SetLogLevel_Handler,
		},
		{
			MethodName: "GetLogLevel",
			Handler:    _HTTPFilter_GetLogLevel_Handler,
		},
		{
			MethodName: "StartKeyLog",
			Handler:    _HTTPFilter_StartKeyLog_Handler,
		},
		{
			MethodName: "StopKeyLog",
			Handler:    _HTTPFilter_StopKeyLog_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _HTTPFilter_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	Monitor_Status_FullMethodName   = "/abox.Monitor/Status"
	Monitor_Shutdown_FullMethodName = "/abox.Monitor/Shutdown"
)

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Monitor Service - manages Tetragon event streaming
type MonitorClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatus, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type monitorClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorClient(cc grpc.ClientConnInterface) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorStatus)
	err := c.cc.Invoke(ctx, Monitor_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Monitor_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
// All implementations must embed UnimplementedMonitorServer
// for forward compatibility.
//
// Monitor Service - manages Tetragon event streaming
type MonitorServer interface {
	Status(context.Context, *Empty) (*MonitorStatus, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedMonitorServer()
}

// UnimplementedMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServer struct{}

func (UnimplementedMonitorServer) Status(context.Context, *Empty) (*MonitorStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMonitorServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedMonitorServer) mustEmbedUnimplementedMonitorServer() {}
func (UnimplementedMonitorServer) testEmbeddedByValue()                 {}

// UnsafeMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServer will
// result in compilation errors.
type UnsafeMonitorServer interface {
	mustEmbedUnimplementedMonitorServer()
}

func RegisterMonitorServer(s grpc.ServiceRegistrar, srv MonitorServer) {
	// If the following call panics, it indicates UnimplementedMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Monitor_ServiceDesc, srv)
}

func _Monitor_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitor_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitor_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Monitor_ServiceDesc is the grpc.ServiceDesc for Monitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Monitor_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Monitor_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}
