// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/rpc/abox.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_rpc_abox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{0}
}

type StringMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMsg) Reset() {
	*x = StringMsg{}
	mi := &file_internal_rpc_abox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMsg) ProtoMessage() {}

func (x *StringMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMsg.ProtoReflect.Descriptor instead.
func (*StringMsg) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{1}
}

func (x *StringMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PathReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathReq) Reset() {
	*x = PathReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathReq) ProtoMessage() {}

func (x *PathReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathReq.ProtoReflect.Descriptor instead.
func (*PathReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{2}
}

func (x *PathReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DomainReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainReq) Reset() {
	*x = DomainReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainReq) ProtoMessage() {}

func (x *DomainReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainReq.ProtoReflect.Descriptor instead.
func (*DomainReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{3}
}

func (x *DomainReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DomainList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainList) Reset() {
	*x = DomainList{}
	mi := &file_internal_rpc_abox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainList) ProtoMessage() {}

func (x *DomainList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainList.ProtoReflect.Descriptor instead.
func (*DomainList) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{4}
}

func (x *DomainList) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

// Privilege-specific messages
type QemuImgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackingFile   string                 `protobuf:"bytes,1,opt,name=backing_file,json=backingFile,proto3" json:"backing_file,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QemuImgReq) Reset() {
	*x = QemuImgReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QemuImgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QemuImgReq) ProtoMessage() {}

func (x *QemuImgReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QemuImgReq.ProtoReflect.Descriptor instead.
func (*QemuImgReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{5}
}

func (x *QemuImgReq) GetBackingFile() string {
	if x != nil {
		return x.BackingFile
	}
	return ""
}

func (x *QemuImgReq) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *QemuImgReq) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type ChmodReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodReq) Reset() {
	*x = ChmodReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodReq) ProtoMessage() {}

func (x *ChmodReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodReq.ProtoReflect.Descriptor instead.
func (*ChmodReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{6}
}

func (x *ChmodReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type MkdirReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirReq) Reset() {
	*x = MkdirReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirReq) ProtoMessage() {}

func (x *MkdirReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirReq.ProtoReflect.Descriptor instead.
func (*MkdirReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{7}
}

func (x *MkdirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type CopyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyReq) Reset() {
	*x = CopyReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyReq) ProtoMessage() {}

func (x *CopyReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyReq.ProtoReflect.Descriptor instead.
func (*CopyReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{8}
}

func (x *CopyReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyReq) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type UfwReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UfwReq) Reset() {
	*x = UfwReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UfwReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UfwReq) ProtoMessage() {}

func (x *UfwReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UfwReq.ProtoReflect.Descriptor instead.
func (*UfwReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{9}
}

func (x *UfwReq) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

type UfwStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UfwStatusResp) Reset() {
	*x = UfwStatusResp{}
	mi := &file_internal_rpc_abox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UfwStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UfwStatusResp) ProtoMessage() {}

func (x *UfwStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UfwStatusResp.ProtoReflect.Descriptor instead.
func (*UfwStatusResp) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{10}
}

func (x *UfwStatusResp) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *UfwStatusResp) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type IptablesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	DnsPort       int32                  `protobuf:"varint,2,opt,name=dns_port,json=dnsPort,proto3" json:"dns_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IptablesReq) Reset() {
	*x = IptablesReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IptablesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IptablesReq) ProtoMessage() {}

func (x *IptablesReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IptablesReq.ProtoReflect.Descriptor instead.
func (*IptablesReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{11}
}

func (x *IptablesReq) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *IptablesReq) GetDnsPort() int32 {
	if x != nil {
		return x.DnsPort
	}
	return 0
}

func (x *IptablesReq) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type IptablesFlushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IptablesFlushReq) Reset() {
	*x = IptablesFlushReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IptablesFlushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IptablesFlushReq) ProtoMessage() {}

func (x *IptablesFlushReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IptablesFlushReq.ProtoReflect.Descriptor instead.
func (*IptablesFlushReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{12}
}

func (x *IptablesFlushReq) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

// DNS-specific messages
type ModeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeReq) Reset() {
	*x = ModeReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeReq) ProtoMessage() {}

func (x *ModeReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeReq.ProtoReflect.Descriptor instead.
func (*ModeReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{13}
}

func (x *ModeReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subcommand    string                 `protobuf:"bytes,1,opt,name=subcommand,proto3" json:"subcommand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReq) Reset() {
	*x = ProfileReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReq) ProtoMessage() {}

func (x *ProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReq.ProtoReflect.Descriptor instead.
func (*ProfileReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{14}
}

func (x *ProfileReq) GetSubcommand() string {
	if x != nil {
		return x.Subcommand
	}
	return ""
}

type ProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResp) Reset() {
	*x = ProfileResp{}
	mi := &file_internal_rpc_abox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResp) ProtoMessage() {}

func (x *ProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResp.ProtoReflect.Descriptor instead.
func (*ProfileResp) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{15}
}

func (x *ProfileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProfileResp) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ProfileResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DNSStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Domains        int32                  `protobuf:"varint,2,opt,name=domains,proto3" json:"domains,omitempty"`
	TotalQueries   uint64                 `protobuf:"varint,3,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	AllowedQueries uint64                 `protobuf:"varint,4,opt,name=allowed_queries,json=allowedQueries,proto3" json:"allowed_queries,omitempty"`
	BlockedQueries uint64                 `protobuf:"varint,5,opt,name=blocked_queries,json=blockedQueries,proto3" json:"blocked_queries,omitempty"`
	CacheHits      uint64                 `protobuf:"varint,6,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	Uptime         string                 `protobuf:"bytes,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	DnsPort        int32                  `protobuf:"varint,8,opt,name=dns_port,json=dnsPort,proto3" json:"dns_port,omitempty"` // The actual port dnsfilter is listening on
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DNSStatus) Reset() {
	*x = DNSStatus{}
	mi := &file_internal_rpc_abox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSStatus) ProtoMessage() {}

func (x *DNSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSStatus.ProtoReflect.Descriptor instead.
func (*DNSStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{16}
}

func (x *DNSStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DNSStatus) GetDomains() int32 {
	if x != nil {
		return x.Domains
	}
	return 0
}

func (x *DNSStatus) GetTotalQueries() uint64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *DNSStatus) GetAllowedQueries() uint64 {
	if x != nil {
		return x.AllowedQueries
	}
	return 0
}

func (x *DNSStatus) GetBlockedQueries() uint64 {
	if x != nil {
		return x.BlockedQueries
	}
	return 0
}

func (x *DNSStatus) GetCacheHits() uint64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *DNSStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *DNSStatus) GetDnsPort() int32 {
	if x != nil {
		return x.DnsPort
	}
	return 0
}

type HTTPStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Mode            string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Domains         int32                  `protobuf:"varint,2,opt,name=domains,proto3" json:"domains,omitempty"`
	TotalRequests   uint64                 `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AllowedRequests uint64                 `protobuf:"varint,4,opt,name=allowed_requests,json=allowedRequests,proto3" json:"allowed_requests,omitempty"`
	BlockedRequests uint64                 `protobuf:"varint,5,opt,name=blocked_requests,json=blockedRequests,proto3" json:"blocked_requests,omitempty"`
	Uptime          string                 `protobuf:"bytes,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	HttpPort        int32                  `protobuf:"varint,7,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`          // The actual port httpfilter is listening on
	MitmEnabled     bool                   `protobuf:"varint,8,opt,name=mitm_enabled,json=mitmEnabled,proto3" json:"mitm_enabled,omitempty"` // Whether TLS MITM interception is active
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HTTPStatus) Reset() {
	*x = HTTPStatus{}
	mi := &file_internal_rpc_abox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPStatus) ProtoMessage() {}

func (x *HTTPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPStatus.ProtoReflect.Descriptor instead.
func (*HTTPStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{17}
}

func (x *HTTPStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HTTPStatus) GetDomains() int32 {
	if x != nil {
		return x.Domains
	}
	return 0
}

func (x *HTTPStatus) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *HTTPStatus) GetAllowedRequests() uint64 {
	if x != nil {
		return x.AllowedRequests
	}
	return 0
}

func (x *HTTPStatus) GetBlockedRequests() uint64 {
	if x != nil {
		return x.BlockedRequests
	}
	return 0
}

func (x *HTTPStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HTTPStatus) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

func (x *HTTPStatus) GetMitmEnabled() bool {
	if x != nil {
		return x.MitmEnabled
	}
	return false
}

// TLS key log messages
type KeyLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyLogReq) Reset() {
	*x = KeyLogReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLogReq) ProtoMessage() {}

func (x *KeyLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLogReq.ProtoReflect.Descriptor instead.
func (*KeyLogReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{18}
}

func (x *KeyLogReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Log level messages
type LogLevelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelReq) Reset() {
	*x = LogLevelReq{}
	mi := &file_internal_rpc_abox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelReq) ProtoMessage() {}

func (x *LogLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelReq.ProtoReflect.Descriptor instead.
func (*LogLevelReq) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{19}
}

func (x *LogLevelReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type LogLevelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelResp) Reset() {
	*x = LogLevelResp{}
	mi := &file_internal_rpc_abox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelResp) ProtoMessage() {}

func (x *LogLevelResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelResp.ProtoReflect.Descriptor instead.
func (*LogLevelResp) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{20}
}

func (x *LogLevelResp) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type MonitorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	EventsLogged  uint64                 `protobuf:"varint,2,opt,name=events_logged,json=eventsLogged,proto3" json:"events_logged,omitempty"`
	LogFile       string                 `protobuf:"bytes,3,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	LogSizeBytes  int64                  `protobuf:"varint,4,opt,name=log_size_bytes,json=logSizeBytes,proto3" json:"log_size_bytes,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorStatus) Reset() {
	*x = MonitorStatus{}
	mi := &file_internal_rpc_abox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorStatus) ProtoMessage() {}

func (x *MonitorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_abox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorStatus.ProtoReflect.Descriptor instead.
func (*MonitorStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpc_abox_proto_rawDescGZIP(), []int{21}
}

func (x *MonitorStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *MonitorStatus) GetEventsLogged() uint64 {
	if x != nil {
		return x.EventsLogged
	}
	return 0
}

func (x *MonitorStatus) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *MonitorStatus) GetLogSizeBytes() int64 {
	if x != nil {
		return x.LogSizeBytes
	}
	return 0
}

func (x *MonitorStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

var File_internal_rpc_abox_proto protoreflect.FileDescriptor

const file_internal_rpc_abox_proto_rawDesc = "" +
	"\n" +
	"\x17internal/rpc/abox.proto\x12\x04abox\"\a\n" +
	"\x05Empty\"%\n" +
	"\tStringMsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1d\n" +
	"\aPathReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\tDomainReq\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"&\n" +
	"\n" +
	"DomainList\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"[\n" +
	"\n" +
	"QemuImgReq\x12!\n" +
	"\fbacking_file\x18\x01 \x01(\tR\vbackingFile\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\"2\n" +
	"\bChmodReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"2\n" +
	"\bMkdirReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"-\n" +
	"\aCopyReq\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\" \n" +
	"\x06UfwReq\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\"E\n" +
	"\rUfwStatusResp\x12\x1c\n" +
	"\tinstalled\x18\x01 \x01(\bR\tinstalled\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"\\\n" +
	"\vIptablesReq\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x19\n" +
	"\bdns_port\x18\x02 \x01(\x05R\adnsPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"*\n" +
	"\x10IptablesFlushReq\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\"\x1d\n" +
	"\aModeReq\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\",\n" +
	"\n" +
	"ProfileReq\x12\x1e\n" +
	"\n" +
	"subcommand\x18\x01 \x01(\tR\n" +
	"subcommand\"W\n" +
	"\vProfileResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x82\x02\n" +
	"\tDNSStatus\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x18\n" +
	"\adomains\x18\x02 \x01(\x05R\adomains\x12#\n" +
	"\rtotal_queries\x18\x03 \x01(\x04R\ftotalQueries\x12'\n" +
	"\x0fallowed_queries\x18\x04 \x01(\x04R\x0eallowedQueries\x12'\n" +
	"\x0fblocked_queries\x18\x05 \x01(\x04R\x0eblockedQueries\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x06 \x01(\x04R\tcacheHits\x12\x16\n" +
	"\x06uptime\x18\a \x01(\tR\x06uptime\x12\x19\n" +
	"\bdns_port\x18\b \x01(\x05R\adnsPort\"\x8f\x02\n" +
	"\n" +
	"HTTPStatus\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x18\n" +
	"\adomains\x18\x02 \x01(\x05R\adomains\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x04R\rtotalRequests\x12)\n" +
	"\x10allowed_requests\x18\x04 \x01(\x04R\x0fallowedRequests\x12)\n" +
	"\x10blocked_requests\x18\x05 \x01(\x04R\x0fblockedRequests\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\tR\x06uptime\x12\x1b\n" +
	"\thttp_port\x18\a \x01(\x05R\bhttpPort\x12!\n" +
	"\fmitm_enabled\x18\b \x01(\bR\vmitmEnabled\"\x1f\n" +
	"\tKeyLogReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\vLogLevelReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"$\n" +
	"\fLogLevelResp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"\xa7\x01\n" +
	"\rMonitorStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12#\n" +
	"\revents_logged\x18\x02 \x01(\x04R\feventsLogged\x12\x19\n" +
	"\blog_file\x18\x03 \x01(\tR\alogFile\x12$\n" +
	"\x0elog_size_bytes\x18\x04 \x01(\x03R\flogSizeBytes\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime2\xba\x04\n" +
	"\tPrivilege\x12$\n" +
	"\x04Ping\x12\v.abox.Empty\x1a\x0f.abox.StringMsg\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty\x12.\n" +
	"\rQemuImgCreate\x12\x10.abox.QemuImgReq\x1a\v.abox.Empty\x12$\n" +
	"\x05Chmod\x12\x0e.abox.ChmodReq\x1a\v.abox.Empty\x12'\n" +
	"\bMkdirAll\x12\x0e.abox.MkdirReq\x1a\v.abox.Empty\x12'\n" +
	"\tRemoveAll\x12\r.abox.PathReq\x1a\v.abox.Empty\x12&\n" +
	"\bCopyFile\x12\r.abox.CopyReq\x1a\v.abox.Empty\x12#\n" +
	"\x06UfwAdd\x12\f.abox.UfwReq\x1a\v.abox.Empty\x12&\n" +
	"\tUfwRemove\x12\f.abox.UfwReq\x1a\v.abox.Empty\x12-\n" +
	"\tUfwStatus\x12\v.abox.Empty\x1a\x13.abox.UfwStatusResp\x12-\n" +
	"\vIptablesAdd\x12\x11.abox.IptablesReq\x1a\v.abox.Empty\x120\n" +
	"\x0eIptablesRemove\x12\x11.abox.IptablesReq\x1a\v.abox.Empty\x124\n" +
	"\rIptablesFlush\x12\x16.abox.IptablesFlushReq\x1a\v.abox.Empty2\x97\x02\n" +
	"\tDNSFilter\x12&\n" +
	"\x06Status\x12\v.abox.Empty\x1a\x0f.abox.DNSStatus\x12)\n" +
	"\aSetMode\x12\r.abox.ModeReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\aProfile\x12\x10.abox.ProfileReq\x1a\x11.abox.ProfileResp\x121\n" +
	"\vSetLogLevel\x12\x11.abox.LogLevelReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\vGetLogLevel\x12\v.abox.Empty\x1a\x12.abox.LogLevelResp\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty2\xaf\x01\n" +
	"\tAllowlist\x12'\n" +
	"\x03Add\x12\x0f.abox.DomainReq\x1a\x0f.abox.StringMsg\x12*\n" +
	"\x06Remove\x12\x0f.abox.DomainReq\x1a\x0f.abox.StringMsg\x12%\n" +
	"\x04List\x12\v.abox.Empty\x1a\x10.abox.DomainList\x12&\n" +
	"\x06Reload\x12\v.abox.Empty\x1a\x0f.abox.StringMsg2\xee\x02\n" +
	"\n" +
	"HTTPFilter\x12'\n" +
	"\x06Status\x12\v.abox.Empty\x1a\x10.abox.HTTPStatus\x12)\n" +
	"\aSetMode\x12\r.abox.ModeReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\aProfile\x12\x10.abox.ProfileReq\x1a\x11.abox.ProfileResp\x121\n" +
	"\vSetLogLevel\x12\x11.abox.LogLevelReq\x1a\x0f.abox.StringMsg\x12.\n" +
	"\vGetLogLevel\x12\v.abox.Empty\x1a\x12.abox.LogLevelResp\x12+\n" +
	"\vStartKeyLog\x12\x0f.abox.KeyLogReq\x1a\v.abox.Empty\x12&\n" +
	"\n" +
	"StopKeyLog\x12\v.abox.Empty\x1a\v.abox.Empty\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.Empty2[\n" +
	"\aMonitor\x12*\n" +
	"\x06Status\x12\v.abox.Empty\x1a\x13.abox.MonitorStatus\x12$\n" +
	"\bShutdown\x12\v.abox.Empty\x1a\v.abox.EmptyB(Z&github.com/jcrussell/abox/internal/rpcb\x06proto3"

var (
	file_internal_rpc_abox_proto_rawDescOnce sync.Once
	file_internal_rpc_abox_proto_rawDescData []byte
)

func file_internal_rpc_abox_proto_rawDescGZIP() []byte {
	file_internal_rpc_abox_proto_rawDescOnce.Do(func() {
		file_internal_rpc_abox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_abox_proto_rawDesc), len(file_internal_rpc_abox_proto_rawDesc)))
	})
	return file_internal_rpc_abox_proto_rawDescData
}

var file_internal_rpc_abox_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_rpc_abox_proto_goTypes = []any{
	(*Empty)(nil),            // 0: abox.Empty
	(*StringMsg)(nil),        // 1: abox.StringMsg
	(*PathReq)(nil),          // 2: abox.PathReq
	(*DomainReq)(nil),        // 3: abox.DomainReq
	(*DomainList)(nil),       // 4: abox.DomainList
	(*QemuImgReq)(nil),       // 5: abox.QemuImgReq
	(*ChmodReq)(nil),         // 6: abox.ChmodReq
	(*MkdirReq)(nil),         // 7: abox.MkdirReq
	(*CopyReq)(nil),          // 8: abox.CopyReq
	(*UfwReq)(nil),           // 9: abox.UfwReq
	(*UfwStatusResp)(nil),    // 10: abox.UfwStatusResp
	(*IptablesReq)(nil),      // 11: abox.IptablesReq
	(*IptablesFlushReq)(nil), // 12: abox.IptablesFlushReq
	(*ModeReq)(nil),          // 13: abox.ModeReq
	(*ProfileReq)(nil),       // 14: abox.ProfileReq
	(*ProfileResp)(nil),      // 15: abox.ProfileResp
	(*DNSStatus)(nil),        // 16: abox.DNSStatus
	(*HTTPStatus)(nil),       // 17: abox.HTTPStatus
	(*KeyLogReq)(nil),        // 18: abox.KeyLogReq
	(*LogLevelReq)(nil),      // 19: abox.LogLevelReq
	(*LogLevelResp)(nil),     // 20: abox.LogLevelResp
	(*MonitorStatus)(nil),    // 21: abox.MonitorStatus
}
var file_internal_rpc_abox_proto_depIdxs = []int32{
	0,  // 0: abox.Privilege.Ping:input_type -> abox.Empty
	0,  // 1: abox.Privilege.Shutdown:input_type -> abox.Empty
	5,  // 2: abox.Privilege.QemuImgCreate:input_type -> abox.QemuImgReq
	6,  // 3: abox.Privilege.Chmod:input_type -> abox.ChmodReq
	7,  // 4: abox.Privilege.MkdirAll:input_type -> abox.MkdirReq
	2,  // 5: abox.Privilege.RemoveAll:input_type -> abox.PathReq
	8,  // 6: abox.Privilege.CopyFile:input_type -> abox.CopyReq
	9,  // 7: abox.Privilege.UfwAdd:input_type -> abox.UfwReq
	9,  // 8: abox.Privilege.UfwRemove:input_type -> abox.UfwReq
	0,  // 9: abox.Privilege.UfwStatus:input_type -> abox.Empty
	11, // 10: abox.Privilege.IptablesAdd:input_type -> abox.IptablesReq
	11, // 11: abox.Privilege.IptablesRemove:input_type -> abox.IptablesReq
	12, // 12: abox.Privilege.IptablesFlush:input_type -> abox.IptablesFlushReq
	0,  // 13: abox.DNSFilter.Status:input_type -> abox.Empty
	13, // 14: abox.DNSFilter.SetMode:input_type -> abox.ModeReq
	14, // 15: abox.DNSFilter.Profile:input_type -> abox.ProfileReq
	19, // 16: abox.DNSFilter.SetLogLevel:input_type -> abox.LogLevelReq
	0,  // 17: abox.DNSFilter.GetLogLevel:input_type -> abox.Empty
	0,  // 18: abox.DNSFilter.Shutdown:input_type -> abox.Empty
	3,  // 19: abox.Allowlist.Add:input_type -> abox.DomainReq
	3,  // 20: abox.Allowlist.Remove:input_type -> abox.DomainReq
	0,  // 21: abox.Allowlist.List:input_type -> abox.Empty
	0,  // 22: abox.Allowlist.Reload:input_type -> abox.Empty
	0,  // 23: abox.HTTPFilter.Status:input_type -> abox.Empty
	13, // 24: abox.HTTPFilter.SetMode:input_type -> abox.ModeReq
	14, // 25: abox.HTTPFilter.Profile:input_type -> abox.ProfileReq
	19, // 26: abox.HTTPFilter.SetLogLevel:input_type -> abox.LogLevelReq
	0,  // 27: abox.HTTPFilter.GetLogLevel:input_type -> abox.Empty
	18, // 28: abox.HTTPFilter.StartKeyLog:input_type -> abox.KeyLogReq
	0,  // 29: abox.HTTPFilter.StopKeyLog:input_type -> abox.Empty
	0,  // 30: abox.HTTPFilter.Shutdown:input_type -> abox.Empty
	0,  // 31: abox.Monitor.Status:input_type -> abox.Empty
	0,  // 32: abox.Monitor.Shutdown:input_type -> abox.Empty
	1,  // 33: abox.Privilege.Ping:output_type -> abox.StringMsg
	0,  // 34: abox.Privilege.Shutdown:output_type -> abox.Empty
	0,  // 35: abox.Privilege.QemuImgCreate:output_type -> abox.Empty
	0,  // 36: abox.Privilege.Chmod:output_type -> abox.Empty
	0,  // 37: abox.Privilege.MkdirAll:output_type -> abox.Empty
	0,  // 38: abox.Privilege.RemoveAll:output_type -> abox.Empty
	0,  // 39: abox.Privilege.CopyFile:output_type -> abox.Empty
	0,  // 40: abox.Privilege.UfwAdd:output_type -> abox.Empty
	0,  // 41: abox.Privilege.UfwRemove:output_type -> abox.Empty
	10, // 42: abox.Privilege.UfwStatus:output_type -> abox.UfwStatusResp
	0,  // 43: abox.Privilege.IptablesAdd:output_type -> abox.Empty
	0,  // 44: abox.Privilege.IptablesRemove:output_type -> abox.Empty
	0,  // 45: abox.Privilege.IptablesFlush:output_type -> abox.Empty
	16, // 46: abox.DNSFilter.Status:output_type -> abox.DNSStatus
	1,  // 47: abox.DNSFilter.SetMode:output_type -> abox.StringMsg
	15, // 48: abox.DNSFilter.Profile:output_type -> abox.ProfileResp
	1,  // 49: abox.DNSFilter.SetLogLevel:output_type -> abox.StringMsg
	20, // 50: abox.DNSFilter.GetLogLevel:output_type -> abox.LogLevelResp
	0,  // 51: abox.DNSFilter.Shutdown:output_type -> abox.Empty
	1,  // 52: abox.Allowlist.Add:output_type -> abox.StringMsg
	1,  // 53: abox.Allowlist.Remove:output_type -> abox.StringMsg
	4,  // 54: abox.Allowlist.List:output_type -> abox.DomainList
	1,  // 55: abox.Allowlist.Reload:output_type -> abox.StringMsg
	17, // 56: abox.HTTPFilter.Status:output_type -> abox.HTTPStatus
	1,  // 57: abox.HTTPFilter.SetMode:output_type -> abox.StringMsg
	15, // 58: abox.HTTPFilter.Profile:output_type -> abox.ProfileResp
	1,  // 59: abox.HTTPFilter.SetLogLevel:output_type -> abox.StringMsg
	20, // 60: abox.HTTPFilter.GetLogLevel:output_type -> abox.LogLevelResp
	0,  // 61: abox.HTTPFilter.StartKeyLog:output_type -> abox.Empty
	0,  // 62: abox.HTTPFilter.StopKeyLog:output_type -> abox.Empty
	0,  // 63: abox.HTTPFilter.Shutdown:output_type -> abox.Empty
	21, // 64: abox.Monitor.Status:output_type -> abox.MonitorStatus
	0,  // 65: abox.Monitor.Shutdown:output_type -> abox.Empty
	33, // [33:66] is the sub-list for method output_type
	0,  // [0:33] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_rpc_abox_proto_init() }
func file_internal_rpc_abox_proto_init() {
	if File_internal_rpc_abox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_abox_proto_rawDesc), len(file_internal_rpc_abox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_internal_rpc_abox_proto_goTypes,
		DependencyIndexes: file_internal_rpc_abox_proto_depIdxs,
		MessageInfos:      file_internal_rpc_abox_proto_msgTypes,
	}.Build()
	File_internal_rpc_abox_proto = out.File
	file_internal_rpc_abox_proto_goTypes = nil
	file_internal_rpc_abox_proto_depIdxs = nil
}
