// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/rpc/abox.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Privilege_Ping_FullMethodName           = "/abox.Privilege/Ping"
	Privilege_Shutdown_FullMethodName       = "/abox.Privilege/Shutdown"
	Privilege_QemuImgCreate_FullMethodName  = "/abox.Privilege/QemuImgCreate"
	Privilege_Chmod_FullMethodName          = "/abox.Privilege/Chmod"
	Privilege_MkdirAll_FullMethodName       = "/abox.Privilege/MkdirAll"
	Privilege_RemoveAll_FullMethodName      = "/abox.Privilege/RemoveAll"
	Privilege_CopyFile_FullMethodName       = "/abox.Privilege/CopyFile"
	Privilege_UfwAdd_FullMethodName         = "/abox.Privilege/UfwAdd"
	Privilege_UfwRemove_FullMethodName      = "/abox.Privilege/UfwRemove"
	Privilege_UfwStatus_FullMethodName      = "/abox.Privilege/UfwStatus"
	Privilege_IptablesAdd_FullMethodName    = "/abox.Privilege/IptablesAdd"
	Privilege_IptablesRemove_FullMethodName = "/abox.Privilege/IptablesRemove"
	Privilege_IptablesFlush_FullMethodName  = "/abox.Privilege/IptablesFlush"
)

// PrivilegeClient is the client API for Privilege service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Privilege Helper Service - runs as root for privileged operations
type PrivilegeClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	QemuImgCreate(ctx context.Context, in *QemuImgReq, opts ...grpc.CallOption) (*Empty, error)
	Chmod(ctx context.Context, in *ChmodReq, opts ...grpc.CallOption) (*Empty, error)
	MkdirAll(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*Empty, error)
	RemoveAll(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*Empty, error)
	CopyFile(ctx context.Context, in *CopyReq, opts ...grpc.CallOption) (*Empty, error)
	UfwAdd(ctx context.Context, in *UfwReq, opts ...grpc.CallOption) (*Empty, error)
	UfwRemove(ctx context.Context, in *UfwReq, opts ...grpc.CallOption) (*Empty, error)
	UfwStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UfwStatusResp, error)
	IptablesAdd(ctx context.Context, in *IptablesReq, opts ...grpc.CallOption) (*Empty, error)
	IptablesRemove(ctx context.Context, in *IptablesReq, opts ...grpc.CallOption) (*Empty, error)
	IptablesFlush(ctx context.Context, in *IptablesFlushReq, opts ...grpc.CallOption) (*Empty, error)
}

type privilegeClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivilegeClient(cc grpc.ClientConnInterface) PrivilegeClient {
	return &privilegeClient{cc}
}

func (c *privilegeClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Privilege_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) QemuImgCreate(ctx context.Context, in *QemuImgReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_QemuImgCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) Chmod(ctx context.Context, in *ChmodReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_Chmod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) MkdirAll(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_MkdirAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) RemoveAll(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_RemoveAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) CopyFile(ctx context.Context, in *CopyReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) UfwAdd(ctx context.Context, in *UfwReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_UfwAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) UfwRemove(ctx context.Context, in *UfwReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_UfwRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) UfwStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UfwStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UfwStatusResp)
	err := c.cc.Invoke(ctx, Privilege_UfwStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) IptablesAdd(ctx context.Context, in *IptablesReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_IptablesAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) IptablesRemove(ctx context.Context, in *IptablesReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_IptablesRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privilegeClient) IptablesFlush(ctx context.Context, in *IptablesFlushReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Privilege_IptablesFlush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivilegeServer is the server API for Privilege service.
// All implementations must embed UnimplementedPrivilegeServer
// for forward compatibility.
//
// Privilege Helper Service - runs as root for privileged operations
type PrivilegeServer interface {
	Ping(context.Context, *Empty) (*StringMsg, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	QemuImgCreate(context.Context, *QemuImgReq) (*Empty, error)
	Chmod(context.Context, *ChmodReq) (*Empty, error)
	MkdirAll(context.Context, *MkdirReq) (*Empty, error)
	RemoveAll(context.Context, *PathReq) (*Empty, error)
	CopyFile(context.Context, *CopyReq) (*Empty, error)
	UfwAdd(context.Context, *UfwReq) (*Empty, error)
	UfwRemove(context.Context, *UfwReq) (*Empty, error)
	UfwStatus(context.Context, *Empty) (*UfwStatusResp, error)
	IptablesAdd(context.Context, *IptablesReq) (*Empty, error)
	IptablesRemove(context.Context, *IptablesReq) (*Empty, error)
	IptablesFlush(context.Context, *IptablesFlushReq) (*Empty, error)
	mustEmbedUnimplementedPrivilegeServer()
}

// UnimplementedPrivilegeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivilegeServer struct{}

func (UnimplementedPrivilegeServer) Ping(context.Context, *Empty) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPrivilegeServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPrivilegeServer) QemuImgCreate(context.Context, *QemuImgReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method QemuImgCreate not implemented")
}
func (UnimplementedPrivilegeServer) Chmod(context.Context, *ChmodReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Chmod not implemented")
}
func (UnimplementedPrivilegeServer) MkdirAll(context.Context, *MkdirReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MkdirAll not implemented")
}
func (UnimplementedPrivilegeServer) RemoveAll(context.Context, *PathReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAll not implemented")
}
func (UnimplementedPrivilegeServer) CopyFile(context.Context, *CopyReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedPrivilegeServer) UfwAdd(context.Context, *UfwReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UfwAdd not implemented")
}
func (UnimplementedPrivilegeServer) UfwRemove(context.Context, *UfwReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UfwRemove not implemented")
}
func (UnimplementedPrivilegeServer) UfwStatus(context.Context, *Empty) (*UfwStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UfwStatus not implemented")
}
func (UnimplementedPrivilegeServer) IptablesAdd(context.Context, *IptablesReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IptablesAdd not implemented")
}
func (UnimplementedPrivilegeServer) IptablesRemove(context.Context, *IptablesReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IptablesRemove not implemented")
}
func (UnimplementedPrivilegeServer) IptablesFlush(context.Context, *IptablesFlushReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IptablesFlush not implemented")
}
func (UnimplementedPrivilegeServer) mustEmbedUnimplementedPrivilegeServer() {}
func (UnimplementedPrivilegeServer) testEmbeddedByValue()                   {}

// UnsafePrivilegeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivilegeServer will
// result in compilation errors.
type UnsafePrivilegeServer interface {
	mustEmbedUnimplementedPrivilegeServer()
}

func RegisterPrivilegeServer(s grpc.ServiceRegistrar, srv PrivilegeServer) {
	// If the following call panics, it indicates UnimplementedPrivilegeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Privilege_ServiceDesc, srv)
}

func _Privilege_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_QemuImgCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QemuImgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).QemuImgCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_QemuImgCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).QemuImgCreate(ctx, req.(*QemuImgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_Chmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChmodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).Chmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_Chmod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).Chmod(ctx, req.(*ChmodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_MkdirAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).MkdirAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_MkdirAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).MkdirAll(ctx, req.(*MkdirReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_RemoveAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).RemoveAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_RemoveAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).RemoveAll(ctx, req.(*PathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).CopyFile(ctx, req.(*CopyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_UfwAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UfwReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).UfwAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_UfwAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).UfwAdd(ctx, req.(*UfwReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_UfwRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UfwReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).UfwRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_UfwRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).UfwRemove(ctx, req.(*UfwReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_UfwStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).UfwStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_UfwStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).UfwStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_IptablesAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IptablesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).IptablesAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_IptablesAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).IptablesAdd(ctx, req.(*IptablesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_IptablesRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IptablesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).IptablesRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_IptablesRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).IptablesRemove(ctx, req.(*IptablesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privilege_IptablesFlush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IptablesFlushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivilegeServer).IptablesFlush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Privilege_IptablesFlush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivilegeServer).IptablesFlush(ctx, req.(*IptablesFlushReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Privilege_ServiceDesc is the grpc.ServiceDesc for Privilege service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Privilege_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Privilege",
	HandlerType: (*PrivilegeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Privilege_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Privilege_Shutdown_Handler,
		},
		{
			MethodName: "QemuImgCreate",
			Handler:    _Privilege_QemuImgCreate_Handler,
		},
		{
			MethodName: "Chmod",
			Handler:    _Privilege_Chmod_Handler,
		},
		{
			MethodName: "MkdirAll",
			Handler:    _Privilege_MkdirAll_Handler,
		},
		{
			MethodName: "RemoveAll",
			Handler:    _Privilege_RemoveAll_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _Privilege_CopyFile_Handler,
		},
		{
			MethodName: "UfwAdd",
			Handler:    _Privilege_UfwAdd_Handler,
		},
		{
			MethodName: "UfwRemove",
			Handler:    _Privilege_UfwRemove_Handler,
		},
		{
			MethodName: "UfwStatus",
			Handler:    _Privilege_UfwStatus_Handler,
		},
		{
			MethodName: "IptablesAdd",
			Handler:    _Privilege_IptablesAdd_Handler,
		},
		{
			MethodName: "IptablesRemove",
			Handler:    _Privilege_IptablesRemove_Handler,
		},
		{
			MethodName: "IptablesFlush",
			Handler:    _Privilege_IptablesFlush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	DNSFilter_Status_FullMethodName      = "/abox.DNSFilter/Status"
	DNSFilter_SetMode_FullMethodName     = "/abox.DNSFilter/SetMode"
	DNSFilter_Profile_FullMethodName     = "/abox.DNSFilter/Profile"
	DNSFilter_SetLogLevel_FullMethodName = "/abox.DNSFilter/SetLogLevel"
	DNSFilter_GetLogLevel_FullMethodName = "/abox.DNSFilter/GetLogLevel"
	DNSFilter_Shutdown_FullMethodName    = "/abox.DNSFilter/Shutdown"
)

// DNSFilterClient is the client API for DNSFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DNS Filter Service - manages DNS filtering
type DNSFilterClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DNSStatus, error)
	SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error)
	Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error)
	SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error)
	GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type dNSFilterClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSFilterClient(cc grpc.ClientConnInterface) DNSFilterClient {
	return &dNSFilterClient{cc}
}

func (c *dNSFilterClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DNSStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSStatus)
	err := c.cc.Invoke(ctx, DNSFilter_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, DNSFilter_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResp)
	err := c.cc.Invoke(ctx, DNSFilter_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, DNSFilter_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelResp)
	err := c.cc.Invoke(ctx, DNSFilter_GetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSFilterClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DNSFilter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSFilterServer is the server API for DNSFilter service.
// All implementations must embed UnimplementedDNSFilterServer
// for forward compatibility.
//
// DNS Filter Service - manages DNS filtering
type DNSFilterServer interface {
	Status(context.Context, *Empty) (*DNSStatus, error)
	SetMode(context.Context, *ModeReq) (*StringMsg, error)
	Profile(context.Context, *ProfileReq) (*ProfileResp, error)
	SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error)
	GetLogLevel(context.Context, *Empty) (*LogLevelResp, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedDNSFilterServer()
}

// UnimplementedDNSFilterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSFilterServer struct{}

func (UnimplementedDNSFilterServer) Status(context.Context, *Empty) (*DNSStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDNSFilterServer) SetMode(context.Context, *ModeReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedDNSFilterServer) Profile(context.Context, *ProfileReq) (*ProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedDNSFilterServer) SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedDNSFilterServer) GetLogLevel(context.Context, *Empty) (*LogLevelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogLevel not implemented")
}
func (UnimplementedDNSFilterServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDNSFilterServer) mustEmbedUnimplementedDNSFilterServer() {}
func (UnimplementedDNSFilterServer) testEmbeddedByValue()                   {}

// UnsafeDNSFilterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSFilterServer will
// result in compilation errors.
type UnsafeDNSFilterServer interface {
	mustEmbedUnimplementedDNSFilterServer()
}

func RegisterDNSFilterServer(s grpc.ServiceRegistrar, srv DNSFilterServer) {
	// If the following call panics, it indicates UnimplementedDNSFilterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSFilter_ServiceDesc, srv)
}

func _DNSFilter_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).SetMode(ctx, req.(*ModeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).Profile(ctx, req.(*ProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).SetLogLevel(ctx, req.(*LogLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_GetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).GetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_GetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).GetLogLevel(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSFilter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSFilterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSFilter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSFilterServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSFilter_ServiceDesc is the grpc.ServiceDesc for DNSFilter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSFilter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.DNSFilter",
	HandlerType: (*DNSFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _DNSFilter_Status_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _DNSFilter_SetMode_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _DNSFilter_Profile_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _DNSFilter_SetLogLevel_Handler,
		},
		{
			MethodName: "GetLogLevel",
			Handler:    _DNSFilter_GetLogLevel_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DNSFilter_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	Allowlist_Add_FullMethodName    = "/abox.Allowlist/Add"
	Allowlist_Remove_FullMethodName = "/abox.Allowlist/Remove"
	Allowlist_List_FullMethodName   = "/abox.Allowlist/List"
	Allowlist_Reload_FullMethodName = "/abox.Allowlist/Reload"
)

// AllowlistClient is the client API for Allowlist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Allowlist Service - manages shared domain allowlist
// Used by both DNS and HTTP filters
type AllowlistClient interface {
	Add(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error)
	Remove(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainList, error)
	Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error)
}

type allowlistClient struct {
	cc grpc.ClientConnInterface
}

func NewAllowlistClient(cc grpc.ClientConnInterface) AllowlistClient {
	return &allowlistClient{cc}
}

func (c *allowlistClient) Add(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Allowlist_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *allowlistClient) Remove(ctx context.Context, in *DomainReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Allowlist_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *allowlistClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainList)
	err := c.cc.Invoke(ctx, Allowlist_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *allowlistClient) Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, Allowlist_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllowlistServer is the server API for Allowlist service.
// All implementations must embed UnimplementedAllowlistServer
// for forward compatibility.
//
// Allowlist Service - manages shared domain allowlist
// Used by both DNS and HTTP filters
type AllowlistServer interface {
	Add(context.Context, *DomainReq) (*StringMsg, error)
	Remove(context.Context, *DomainReq) (*StringMsg, error)
	List(context.Context, *Empty) (*DomainList, error)
	Reload(context.Context, *Empty) (*StringMsg, error)
	mustEmbedUnimplementedAllowlistServer()
}

// UnimplementedAllowlistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAllowlistServer struct{}

func (UnimplementedAllowlistServer) Add(context.Context, *DomainReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAllowlistServer) Remove(context.Context, *DomainReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedAllowlistServer) List(context.Context, *Empty) (*DomainList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAllowlistServer) Reload(context.Context, *Empty) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedAllowlistServer) mustEmbedUnimplementedAllowlistServer() {}
func (UnimplementedAllowlistServer) testEmbeddedByValue()                   {}

// UnsafeAllowlistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AllowlistServer will
// result in compilation errors.
type UnsafeAllowlistServer interface {
	mustEmbedUnimplementedAllowlistServer()
}

func RegisterAllowlistServer(s grpc.ServiceRegistrar, srv AllowlistServer) {
	// If the following call panics, it indicates UnimplementedAllowlistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Allowlist_ServiceDesc, srv)
}

func _Allowlist_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).Add(ctx, req.(*DomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Allowlist_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).Remove(ctx, req.(*DomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Allowlist_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Allowlist_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllowlistServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Allowlist_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllowlistServer).Reload(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Allowlist_ServiceDesc is the grpc.ServiceDesc for Allowlist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Allowlist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Allowlist",
	HandlerType: (*AllowlistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Allowlist_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Allowlist_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Allowlist_List_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _Allowlist_Reload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	HTTPFilter_Status_FullMethodName      = "/abox.HTTPFilter/Status"
	HTTPFilter_SetMode_FullMethodName     = "/abox.HTTPFilter/SetMode"
	HTTPFilter_Profile_FullMethodName     = "/abox.HTTPFilter/Profile"
	HTTPFilter_SetLogLevel_FullMethodName = "/abox.HTTPFilter/SetLogLevel"
	HTTPFilter_GetLogLevel_FullMethodName = "/abox.HTTPFilter/GetLogLevel"
	HTTPFilter_StartKeyLog_FullMethodName = "/abox.HTTPFilter/StartKeyLog"
	HTTPFilter_StopKeyLog_FullMethodName  = "/abox.HTTPFilter/StopKeyLog"
	HTTPFilter_Shutdown_FullMethodName    = "/abox.HTTPFilter/Shutdown"
)

// HTTPFilterClient is the client API for HTTPFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HTTP Filter Service - manages HTTP proxy filtering
type HTTPFilterClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HTTPStatus, error)
	SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error)
	Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error)
	SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error)
	GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error)
	StartKeyLog(ctx context.Context, in *KeyLogReq, opts ...grpc.CallOption) (*Empty, error)
	StopKeyLog(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type hTTPFilterClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPFilterClient(cc grpc.ClientConnInterface) HTTPFilterClient {
	return &hTTPFilterClient{cc}
}

func (c *hTTPFilterClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HTTPStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPStatus)
	err := c.cc.Invoke(ctx, HTTPFilter_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) SetMode(ctx context.Context, in *ModeReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, HTTPFilter_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResp)
	err := c.cc.Invoke(ctx, HTTPFilter_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) SetLogLevel(ctx context.Context, in *LogLevelReq, opts ...grpc.CallOption) (*StringMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, HTTPFilter_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) GetLogLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogLevelResp)
	err := c.cc.Invoke(ctx, HTTPFilter_GetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) StartKeyLog(ctx context.Context, in *KeyLogReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HTTPFilter_StartKeyLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) StopKeyLog(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HTTPFilter_StopKeyLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFilterClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HTTPFilter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPFilterServer is the server API for HTTPFilter service.
// All implementations must embed UnimplementedHTTPFilterServer
// for forward compatibility.
//
// HTTP Filter Service - manages HTTP proxy filtering
type HTTPFilterServer interface {
	Status(context.Context, *Empty) (*HTTPStatus, error)
	SetMode(context.Context, *ModeReq) (*StringMsg, error)
	Profile(context.Context, *ProfileReq) (*ProfileResp, error)
	SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error)
	GetLogLevel(context.Context, *Empty) (*LogLevelResp, error)
	StartKeyLog(context.Context, *KeyLogReq) (*Empty, error)
	StopKeyLog(context.Context, *Empty) (*Empty, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedHTTPFilterServer()
}

// UnimplementedHTTPFilterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPFilterServer struct{}

func (UnimplementedHTTPFilterServer) Status(context.Context, *Empty) (*HTTPStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHTTPFilterServer) SetMode(context.Context, *ModeReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedHTTPFilterServer) Profile(context.Context, *ProfileReq) (*ProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedHTTPFilterServer) SetLogLevel(context.Context, *LogLevelReq) (*StringMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedHTTPFilterServer) GetLogLevel(context.Context, *Empty) (*LogLevelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogLevel not implemented")
}
func (UnimplementedHTTPFilterServer) StartKeyLog(context.Context, *KeyLogReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartKeyLog not implemented")
}
func (UnimplementedHTTPFilterServer) StopKeyLog(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopKeyLog not implemented")
}
func (UnimplementedHTTPFilterServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedHTTPFilterServer) mustEmbedUnimplementedHTTPFilterServer() {}
func (UnimplementedHTTPFilterServer) testEmbeddedByValue()                    {}

// UnsafeHTTPFilterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPFilterServer will
// result in compilation errors.
type UnsafeHTTPFilterServer interface {
	mustEmbedUnimplementedHTTPFilterServer()
}

func RegisterHTTPFilterServer(s grpc.ServiceRegistrar, srv HTTPFilterServer) {
	// If the following call panics, it indicates UnimplementedHTTPFilterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPFilter_ServiceDesc, srv)
}

func _HTTPFilter_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).SetMode(ctx, req.(*ModeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).Profile(ctx, req.(*ProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).SetLogLevel(ctx, req.(*LogLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_GetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).GetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_GetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).GetLogLevel(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_StartKeyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).StartKeyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_StartKeyLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).StartKeyLog(ctx, req.(*KeyLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_StopKeyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).StopKeyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_StopKeyLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).StopKeyLog(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFilter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFilterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFilter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFilterServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPFilter_ServiceDesc is the grpc.ServiceDesc for HTTPFilter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPFilter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.HTTPFilter",
	HandlerType: (*HTTPFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HTTPFilter_Status_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _HTTPFilter_SetMode_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _HTTPFilter_Profile_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _HTTPFilter_SetLogLevel_Handler,
		},
		{
			MethodName: "GetLogLevel",
			Handler:    _HTTPFilter_GetLogLevel_Handler,
		},
		{
			MethodName: "StartKeyLog",
			Handler:    _HTTPFilter_StartKeyLog_Handler,
		},
		{
			MethodName: "StopKeyLog",
			Handler:    _HTTPFilter_StopKeyLog_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _HTTPFilter_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}

const (
	Monitor_Status_FullMethodName   = "/abox.Monitor/Status"
	Monitor_Shutdown_FullMethodName = "/abox.Monitor/Shutdown"
)

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Monitor Service - manages Tetragon event streaming
type MonitorClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatus, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type monitorClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorClient(cc grpc.ClientConnInterface) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorStatus)
	err := c.cc.Invoke(ctx, Monitor_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Monitor_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
// All implementations must embed UnimplementedMonitorServer
// for forward compatibility.
//
// Monitor Service - manages Tetragon event streaming
type MonitorServer interface {
	Status(context.Context, *Empty) (*MonitorStatus, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedMonitorServer()
}

// UnimplementedMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServer struct{}

func (UnimplementedMonitorServer) Status(context.Context, *Empty) (*MonitorStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMonitorServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedMonitorServer) mustEmbedUnimplementedMonitorServer() {}
func (UnimplementedMonitorServer) testEmbeddedByValue()                 {}

// UnsafeMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServer will
// result in compilation errors.
type UnsafeMonitorServer interface {
	mustEmbedUnimplementedMonitorServer()
}

func RegisterMonitorServer(s grpc.ServiceRegistrar, srv MonitorServer) {
	// If the following call panics, it indicates UnimplementedMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Monitor_ServiceDesc, srv)
}

func _Monitor_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitor_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitor_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Monitor_ServiceDesc is the grpc.ServiceDesc for Monitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abox.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Monitor_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Monitor_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/abox.proto",
}
