// Package firewall also adapts the privileged macOS pf helper client. The pf
// client wraps rpc.PfClient (mirroring how egress.go wraps rpc.EgressClient)
// and the rule generator produces the subnet-keyed ruleset the helper's
// validatePFRules accepts token-for-token.
package firewall

import (
	"context"
	"fmt"
	"net"
	"strings"

	"github.com/sandialabs/abox/internal/backend"
	"github.com/sandialabs/abox/internal/logging"
	"github.com/sandialabs/abox/internal/pfvalidate"
	"github.com/sandialabs/abox/internal/rpc"
	"github.com/sandialabs/abox/internal/timeout"
)

// PfClient is the concrete pfctl surface the macOS egress controller drives via
// the injected provider. Asserting it here localizes any signature drift from
// backend.PfEnforcer to this file rather than a distant injection site.
var _ backend.PfEnforcer = (*PfClient)(nil)

// PfClient manages macOS pf firewall rules for per-instance traffic
// interception via the privilege helper RPC. Each instance gets its own pf
// anchor (abox/<instance>) containing DNS redirect rules and a default-deny
// outbound policy with explicit allows for the proxy and ICMP to the gateway
// (there is no DHCP rule: guests are statically addressed via cloud-init and the
// network runs no DHCP server). Rules key on the instance's deterministic /24
// subnet, not the VM IP.
type PfClient struct {
	priv rpc.PfClient
}

// NewPfClient creates a new pf client from an rpc.PfClient.
func NewPfClient(priv rpc.PfClient) *PfClient {
	return &PfClient{priv: priv}
}

// Enable wires the abox anchor references into /etc/pf.conf if not already
// present and enables the pf firewall. Both operations are idempotent.
func (c *PfClient) Enable(ctx context.Context) error {
	cctx, cancel := context.WithTimeout(ctx, timeout.Default)
	defer cancel()

	if _, err := c.priv.Enable(cctx, &rpc.Empty{}); err != nil {
		return fmt.Errorf("failed to enable PF: %w", err)
	}
	logging.Audit("PF enabled", "action", logging.ActionPfctlWireAnchors)
	return nil
}

// LoadAnchor installs the per-instance rule set into abox/<instance>. The rules
// are generated by BuildInstanceRules for the given subnet, so they pass the
// helper's subnet binding token-for-token.
func (c *PfClient) LoadAnchor(ctx context.Context, instance, subnet, rules string) error {
	logging.Debug("loading PF anchor", "instance", instance, "subnet", subnet)

	cctx, cancel := context.WithTimeout(ctx, timeout.Default)
	defer cancel()

	if _, err := c.priv.LoadAnchor(cctx, &rpc.PfAnchorReq{
		Instance: instance,
		Subnet:   subnet,
		Rules:    rules,
	}); err != nil {
		return fmt.Errorf("failed to load PF rules: %w", err)
	}

	logging.Audit("PF instance rules applied",
		"action", logging.ActionPfctlLoadAnchor,
		"instance", instance,
		"subnet", subnet,
	)
	return nil
}

// FlushAnchor removes all rules from the instance's anchor (idempotent).
func (c *PfClient) FlushAnchor(ctx context.Context, instance string) error {
	logging.Debug("flushing PF anchor", "instance", instance)

	cctx, cancel := context.WithTimeout(ctx, timeout.Default)
	defer cancel()

	if _, err := c.priv.FlushAnchor(cctx, &rpc.PfInstanceReq{Instance: instance}); err != nil {
		return fmt.Errorf("failed to flush PF anchor: %w", err)
	}

	logging.Audit("PF instance rules flushed",
		"action", logging.ActionPfctlFlushAnchor,
		"instance", instance,
	)
	return nil
}

// TeardownConfig removes the abox-managed anchor references from /etc/pf.conf
// and reloads the main ruleset.
func (c *PfClient) TeardownConfig(ctx context.Context) error {
	logging.Debug("tearing down PF anchor references in /etc/pf.conf")

	cctx, cancel := context.WithTimeout(ctx, timeout.Default)
	defer cancel()

	if _, err := c.priv.TeardownConfig(cctx, &rpc.Empty{}); err != nil {
		return fmt.Errorf("failed to tear down PF config: %w", err)
	}

	logging.Audit("PF anchor references removed from /etc/pf.conf",
		"action", logging.ActionPfctlTeardown,
	)
	return nil
}

// BuildInstanceRules generates the subnet-keyed pf ruleset for a single
// instance. Every line is emitted exactly as the helper's validatePFRules
// expects it (single-space separated, in this order), and every variable token
// is bound to the caller's subnet:
//
//   - rdr rules redirect VM DNS traffic (subnet -> any :53) to 127.0.0.1:<dnsPort>
//   - an inet6 block on the VM's bridge kills all IPv6 (vmnet has no flag to
//     disable NAT66/link-local v6, which would otherwise leak past the
//     IPv4-only default-deny rule)
//   - pass rules allow the HTTP proxy on the gateway and ICMP to the gateway
//   - one inbound pass allows host->guest SSH (from the gateway to the subnet on
//     port 22); the guest's reply rides pf's default TCP state, so it is admitted
//     before the terminal deny without loosening egress
//   - a "block drop quick ... from ! <subnet> ... port <httpPort>" drops inbound
//     connections to the HTTP proxy from any source outside the instance subnet.
//     The proxy binds the wildcard (the gateway address does not exist when the
//     filter starts), so without this rule a LAN-adjacent host could reach the
//     unauthenticated egress proxy; pf is what confines it to the guest.
//   - a terminal "block drop quick" drops everything else from the subnet
//
// Rules key on the deterministic per-instance /24 subnet (the guest's static
// address is a host within it, so subnet-keying covers it); the gateway is the .1
// host of the subnet. There is no DHCP rule: guests are statically addressed
// (cloud-init) and the network runs no DHCP server. The inbound SSH rule is the
// one exception to the "from <subnet>" shape: it is "from <gateway>", the host's
// address on the bridge (the same address the HTTP-proxy rule targets).
func BuildInstanceRules(subnet, gateway, bridge string, dnsPort, httpPort int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# abox instance traffic rules for %s\n", subnet)
	fmt.Fprintf(&b, "# DNS redirect (VM queries to any :53 -> local dnsfilter)\n")
	fmt.Fprintf(&b, "rdr pass proto udp from %s to any port 53 -> 127.0.0.1 port %d\n", subnet, dnsPort)
	fmt.Fprintf(&b, "rdr pass proto tcp from %s to any port 53 -> 127.0.0.1 port %d\n", subnet, dnsPort)
	fmt.Fprintf(&b, "# Block all IPv6 on this VM's bridge (vmnet has no flag to disable NAT66)\n")
	fmt.Fprintf(&b, "block drop quick on %s inet6 all\n", bridge)
	fmt.Fprintf(&b, "# Allowlisted outbound\n")
	fmt.Fprintf(&b, "pass quick proto tcp from %s to %s port %d\n", subnet, gateway, httpPort)
	fmt.Fprintf(&b, "pass quick proto icmp from %s to %s\n", subnet, gateway)
	fmt.Fprintf(&b, "# Allow host->guest SSH; the reply (subnet->gateway) is admitted by pf state\n")
	fmt.Fprintf(&b, "pass quick proto tcp from %s to %s port 22\n", gateway, subnet)
	fmt.Fprintf(&b, "# Deny inbound to the HTTP proxy from anything outside the instance subnet\n")
	fmt.Fprintf(&b, "block drop quick proto tcp from ! %s to any port %d\n", subnet, httpPort)
	fmt.Fprintf(&b, "# Default deny: everything else from the VM is dropped\n")
	fmt.Fprintf(&b, "block drop quick from %s to any\n", subnet)
	return b.String()
}

// InstanceRules validates the inputs and returns the subnet-keyed ruleset for an
// instance. It is the safe entry point Batch 4's controller will use: it rejects
// malformed subnets/gateways/bridges/ports before they reach the helper (which
// independently re-validates as the trust boundary). BuildInstanceRules is the
// unchecked generator used by tests that need to exercise malformed shapes.
func InstanceRules(instance, subnet, gateway, bridge string, dnsPort, httpPort int) (string, error) {
	if err := validatePfArgs(instance, subnet, gateway, bridge, dnsPort, httpPort); err != nil {
		return "", err
	}
	return BuildInstanceRules(subnet, gateway, bridge, dnsPort, httpPort), nil
}

// BuildPreBootDenyRules generates the minimal pre-boot pf ruleset loaded into the
// per-instance anchor BEFORE the VM boots so the guest is fail-closed from its
// first packet; Apply later replaces the anchor wholesale with the full ruleset
// once the vmnet bridge is known. It contains two lines, both a strict subset of
// BuildInstanceRules:
//
//   - the inbound-proxy confinement "block drop quick proto tcp from ! <subnet>
//     ... port <httpPort>": the HTTP proxy binds the wildcard from the moment the
//     filter starts (before the VM), so without this rule a LAN-adjacent host
//     could reach the unauthenticated egress proxy during the pre-boot→Apply
//     window. Loading it pre-boot closes that open-proxy window.
//   - the subnet-keyed terminal default-deny.
//
// Both denies are IPv4-only: the interface-scoped IPv6 kill needs the vmnet
// bridge, which does not exist pre-boot, so it is added by BuildInstanceRules once
// Apply runs post-boot (the guest is on a host-only, no-uplink network in the
// interim). No allow rules are needed here: the guest is statically addressed (no
// DHCP handshake to permit), which is also why this ruleset stays exempt from the
// helper's inet6-deny requirement (see validatePFRules).
func BuildPreBootDenyRules(subnet string, httpPort int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# abox pre-boot rules for %s (IPv4-only; full rules incl. IPv6 kill load post-boot)\n", subnet)
	fmt.Fprintf(&b, "# Deny inbound to the HTTP proxy from anything outside the instance subnet\n")
	fmt.Fprintf(&b, "block drop quick proto tcp from ! %s to any port %d\n", subnet, httpPort)
	fmt.Fprintf(&b, "# Default deny: everything else from the VM is dropped\n")
	fmt.Fprintf(&b, "block drop quick from %s to any\n", subnet)
	return b.String()
}

// PreBootDenyRules validates the inputs and returns the pre-boot ruleset (see
// BuildPreBootDenyRules). It rejects a malformed instance name, a non-/24 subnet,
// or an out-of-range HTTP port before the rules reach the helper (which
// re-validates as the trust boundary). Unlike InstanceRules it needs no
// gateway/bridge/DNS port — the denies key on the subnet and the proxy port.
func PreBootDenyRules(instance, subnet string, httpPort int) (string, error) {
	if err := pfvalidate.ValidateInstanceName(instance); err != nil {
		return "", err
	}
	if _, _, err := pfvalidate.ParseSubnet24(subnet); err != nil {
		return "", err
	}
	if err := validatePfPort("HTTP", httpPort); err != nil {
		return "", err
	}
	return BuildPreBootDenyRules(subnet, httpPort), nil
}

// validatePfArgs validates the inputs for pf rule generation. The subnet must be
// a /24 CIDR network address and the gateway must be its .1 host, mirroring the
// helper's subnetTokens so the client never generates rules the helper rejects.
// The primitives live in internal/pfvalidate, which the helper validates against
// independently as the trust boundary.
func validatePfArgs(instance, subnet, gateway, bridge string, dnsPort, httpPort int) error {
	if err := pfvalidate.ValidateInstanceName(instance); err != nil {
		return err
	}
	if err := validatePfSubnetGateway(subnet, gateway); err != nil {
		return err
	}
	if !pfvalidate.MatchBridgeName(bridge) {
		return fmt.Errorf("invalid bridge interface %q: must match (bridge|vmnet)[0-9]+", bridge)
	}
	if err := validatePfPort("DNS", dnsPort); err != nil {
		return err
	}
	return validatePfPort("HTTP", httpPort)
}

// validatePfSubnetGateway enforces that subnet is a /24 IPv4 network address and
// gateway is its .1 host. It derives the expected gateway via the shared
// pfvalidate.ParseSubnet24 (the same derivation the helper's subnetTokens uses)
// and then checks the caller-supplied gateway matches it.
func validatePfSubnetGateway(subnet, gateway string) error {
	_, wantGw, err := pfvalidate.ParseSubnet24(subnet)
	if err != nil {
		return err
	}
	gwIP := net.ParseIP(gateway)
	if gwIP == nil || gwIP.To4() == nil {
		return fmt.Errorf("invalid gateway IP %q", gateway)
	}
	if !gwIP.To4().Equal(wantGw) {
		return fmt.Errorf("gateway %q must be the .1 host of subnet %q", gateway, subnet)
	}
	return nil
}

// validatePfPort enforces the 1024-65535 range shared by the DNS and HTTP ports.
func validatePfPort(label string, port int) error {
	if !pfvalidate.ValidatePort(port) {
		return fmt.Errorf("invalid %s port %d: must be 1024-65535", label, port)
	}
	return nil
}
