// Package boxfile provides parsing and validation for abox.yaml configuration files.
package boxfile

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/sandialabs/abox/internal/config"
	"github.com/sandialabs/abox/internal/filterbase"
	"github.com/sandialabs/abox/internal/tetragon/policy"
	"github.com/sandialabs/abox/internal/validation"
)

// CurrentBoxfileVersion is the current version of the abox.yaml format.
const CurrentBoxfileVersion = 1

// overrideKeyTemplate is the overrides.<backend> key holding a custom domain
// template. A custom template bypasses abox's default VM hardening, so the
// trust gate treats it as security-relevant.
const overrideKeyTemplate = "template"

// BoxfileDNS holds DNS-related configuration in abox.yaml.
type BoxfileDNS struct {
	Upstream string `yaml:"upstream,omitempty"` // upstream DNS server
}

// BoxfileMonitor holds monitoring-related configuration in abox.yaml.
type BoxfileMonitor struct {
	Enabled     bool     `yaml:"enabled,omitempty"`      // enable Tetragon monitoring via virtio-serial
	Version     string   `yaml:"version,omitempty"`      // Tetragon version to use (empty = latest)
	KprobeMulti *bool    `yaml:"kprobe_multi,omitempty"` // enable BPF kprobe_multi attachment (default: false)
	Kprobes     []string `yaml:"kprobes,omitempty"`      // curated kprobe names (nil = all defaults); mutually exclusive with Policies
	Policies    []string `yaml:"policies,omitempty"`     // paths to custom TracingPolicy YAML files; mutually exclusive with Kprobes
}

// BoxfileHTTP holds HTTP proxy-related configuration in abox.yaml.
type BoxfileHTTP struct {
	MITM           *bool `yaml:"mitm,omitempty"`            // Enable TLS MITM (default: true). Pointer to distinguish unset from false.
	MaxConnections *int  `yaml:"max_connections,omitempty"` // cap on concurrent client connections (default: 512). Pointer to distinguish unset.
	// AllowPrivateTargets lists CIDRs the DNS/HTTP filters may reach despite the
	// default SSRF deny of private/loopback/link-local/metadata ranges. Empty =
	// deny all such targets (the secure default).
	AllowPrivateTargets []string `yaml:"allow_private_targets,omitempty"`
	// AllowedPorts restricts the destination ports the proxy may reach. Empty =
	// built-in defaults (443 for CONNECT, 80+443 for forward). Widening it is a
	// security-relevant change surfaced by the abox.yaml trust prompt.
	AllowedPorts []int `yaml:"allowed_ports,omitempty"`
	// SecretInjections binds host-side secret store values into outbound request
	// headers (see config.SecretInjection). The value lives in the secret store,
	// never in abox.yaml.
	SecretInjections []config.SecretInjection `yaml:"secret_injections,omitempty"`
	// MITMExceptions lists domains tunneled without TLS interception even when mitm
	// is enabled (for apps that pin certificates). An exception only downgrades an
	// already-allowlisted host from interception to a transparent tunnel; it never
	// grants access, and it forfeits inner-Host/domain-fronting inspection for those
	// domains. A host matches the domain and all its subdomains. Keep the list minimal.
	MITMExceptions []string `yaml:"mitm_exceptions,omitempty"`
}

// Boxfile represents the abox.yaml declarative configuration.
type Boxfile struct {
	Version int    `yaml:"version"`
	Name    string `yaml:"name"`
	// Backend pins the VM backend for this instance (libvirt, vfkit, ...).
	// Empty means auto-detect. ABOX_BACKEND overrides it; experimental backends
	// are rejected here and must be selected via ABOX_BACKEND. omitempty keeps
	// the key out of files generated by `abox init`.
	Backend   string                       `yaml:"backend,omitempty"`
	CPUs      int                          `yaml:"cpus"`
	Memory    int                          `yaml:"memory"`
	Disk      string                       `yaml:"disk"`
	Base      string                       `yaml:"base"`
	User      string                       `yaml:"user"`
	Subnet    string                       `yaml:"subnet"`
	Provision []string                     `yaml:"provision"`
	Overlay   string                       `yaml:"overlay"`
	Allowlist []string                     `yaml:"allowlist,omitempty"` // domain allowlist (shared by DNS and HTTP filters)
	DNS       BoxfileDNS                   `yaml:"dns,omitempty"`
	HTTP      BoxfileHTTP                  `yaml:"http,omitempty"`      // HTTP proxy configuration
	Monitor   BoxfileMonitor               `yaml:"monitor,omitempty"`   // Tetragon monitoring configuration
	Overrides map[string]map[string]string `yaml:"overrides,omitempty"` // backend-specific overrides (e.g., overrides.libvirt.template)

	// srcName is the base name of the file this Boxfile was read from, used so
	// validation errors name the file the user actually passed (create
	// --from-file accepts any filename). Unexported, so yaml ignores it in both
	// directions. Empty for a Boxfile built in memory; see fileName.
	srcName string
}

// fileName returns the file this Boxfile came from, for error messages.
func (b *Boxfile) fileName() string {
	if b.srcName == "" {
		return "abox.yaml"
	}
	return b.srcName
}

// DefaultBoxfile returns a Boxfile with default values.
func DefaultBoxfile() *Boxfile {
	mitmDefault := true
	return &Boxfile{
		Version: CurrentBoxfileVersion,
		CPUs:    2,
		Memory:  4096,
		Disk:    config.DefaultDisk,
		Base:    config.DefaultBase,
		User:    "ubuntu",
		DNS: BoxfileDNS{
			Upstream: config.DefaultUpstream,
		},
		HTTP: BoxfileHTTP{
			MITM: &mitmDefault,
		},
	}
}

// GetKprobeMulti returns whether kprobe_multi is enabled, defaulting to false if not set.
func (b *Boxfile) GetKprobeMulti() bool {
	if b.Monitor.KprobeMulti != nil {
		return *b.Monitor.KprobeMulti
	}
	return false // default: disabled for reliability
}

// GetMITM returns whether MITM is enabled, defaulting to true if not set.
func (b *Boxfile) GetMITM() bool {
	if b.HTTP.MITM == nil {
		return true // Default to enabled for security
	}
	return *b.HTTP.MITM
}

// GetMaxConnections returns the HTTP proxy connection cap, defaulting to
// config.DefaultHTTPMaxConnections if not set.
func (b *Boxfile) GetMaxConnections() int {
	if b.HTTP.MaxConnections == nil {
		return config.DefaultHTTPMaxConnections
	}
	return *b.HTTP.MaxConnections
}

// GetAllowPrivateTargets returns the opt-in list of permitted private-target
// CIDRs (empty by default = deny all private/loopback/link-local/metadata).
func (b *Boxfile) GetAllowPrivateTargets() []string {
	return b.HTTP.AllowPrivateTargets
}

// GetSecretInjections returns the configured secret-injection bindings (nil if
// none are set).
func (b *Boxfile) GetSecretInjections() []config.SecretInjection {
	return b.HTTP.SecretInjections
}

// GetMITMExceptions returns the domains that bypass TLS interception (nil if none
// are set).
func (b *Boxfile) GetMITMExceptions() []string {
	return b.HTTP.MITMExceptions
}

// GetAllowedPorts returns the configured destination-port allow-list (nil if
// unset = the proxy's built-in defaults).
func (b *Boxfile) GetAllowedPorts() []int {
	return b.HTTP.AllowedPorts
}

// Load reads abox.yaml from the specified directory (or current directory if empty).
// Returns the parsed Boxfile and the directory containing the file.
func Load(dir string) (*Boxfile, string, error) {
	box, absDir, _, err := LoadRaw(dir)
	return box, absDir, err
}

// LoadRaw is Load plus the exact raw abox.yaml bytes that were parsed. The trust
// gate (see trust.go) fingerprints THESE bytes — never a second os.ReadFile — so
// the recorded fingerprint always attests to the bytes actually used (no TOCTOU
// between the hashed content and the parsed content).
func LoadRaw(dir string) (*Boxfile, string, []byte, error) {
	if dir == "" {
		var err error
		dir, err = os.Getwd()
		if err != nil {
			return nil, "", nil, fmt.Errorf("failed to get current directory: %w", err)
		}
	}

	// Convert to absolute path
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return nil, "", nil, fmt.Errorf("failed to resolve path: %w", err)
	}

	return loadFile(filepath.Join(absDir, "abox.yaml"), true)
}

// LoadLenient reads abox.yaml like Load but skips the checks that exist to
// protect a *new* instance: unknown keys, the version gate, and the
// single-document rule are all tolerated.
//
// It exists for teardown (abox down), which needs nothing but the instance name
// out of the file. Failing there would leave a user unable to stop a running VM
// with the command they have been using, so teardown stays readable even when
// the file no longer parses strictly or targets a newer abox. Commands that
// create or configure an instance must use Load: silently ignoring a key there means a
// security setting the user asked for is quietly not applied.
func LoadLenient(dir string) (*Boxfile, string, error) {
	if dir == "" {
		var err error
		dir, err = os.Getwd()
		if err != nil {
			return nil, "", fmt.Errorf("failed to get current directory: %w", err)
		}
	}

	absDir, err := filepath.Abs(dir)
	if err != nil {
		return nil, "", fmt.Errorf("failed to resolve path: %w", err)
	}

	box, absDir, _, err := loadFile(filepath.Join(absDir, "abox.yaml"), false)
	return box, absDir, err
}

// LoadFile reads a boxfile from an explicit path rather than looking for
// "abox.yaml" in a directory. Returns the parsed Boxfile and the directory
// containing it, which is the base for the relative provision/overlay/policy/
// override paths inside it.
//
// Callers that accept a user-supplied filename (create --from-file) must use
// this rather than Load(filepath.Dir(path)): Load always reads "abox.yaml", so
// routing a named file through it silently loads a different file.
func LoadFile(path string) (*Boxfile, string, error) {
	box, absDir, _, err := loadFile(path, true)
	return box, absDir, err
}

// LoadFileRaw is LoadFile plus the exact raw bytes that were parsed, with the
// same TOCTOU guarantee as LoadRaw: the trust gate fingerprints these bytes,
// never a second os.ReadFile.
func LoadFileRaw(path string) (*Boxfile, string, []byte, error) {
	return loadFile(path, true)
}

// loadFile parses a boxfile. When strict, unknown keys are rejected (see
// decodeError); otherwise they are ignored, which is the historical behavior.
// The returned []byte is the exact raw content that was parsed, for the trust
// fingerprint (see LoadRaw).
func loadFile(path string, strict bool) (*Boxfile, string, []byte, error) {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return nil, "", nil, fmt.Errorf("failed to resolve path: %w", err)
	}
	absDir := filepath.Dir(absPath)
	name := filepath.Base(absPath)

	data, err := os.ReadFile(absPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, "", nil, fmt.Errorf("%s not found in %s", name, absDir)
		}
		return nil, "", nil, fmt.Errorf("failed to read %s: %w", name, err)
	}

	// Pass 1: permissive, to read the version before anything can reject the
	// file. Deliberately not strict: a boxfile written by a newer abox must
	// reach the version check below and be told to upgrade, rather than being
	// buried under unknown-key errors for keys that abox simply doesn't have yet.
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, "", nil, fmt.Errorf("failed to parse %s: %w", name, err)
	}
	// The version gate and the single-document check are skipped when lenient:
	// the lenient caller (teardown) only needs the instance name, and a version
	// it cannot satisfy or a stray document separator must not stand between the
	// user and stopping a running VM.
	if strict {
		if err := checkBoxfileVersion(name, raw); err != nil {
			return nil, "", nil, err
		}
	}

	// Pass 2: decode over the defaults.
	box := DefaultBoxfile()
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(strict)
	if err := dec.Decode(box); err != nil && !errors.Is(err, io.EOF) {
		// Lenient callers tolerate content errors too, not just unknown keys.
		// yaml reports type mismatches as a *yaml.TypeError only after decoding
		// everything it could, so box still holds the fields that did parse —
		// which is all teardown needs. Anything else (malformed YAML) is fatal
		// either way, since there is nothing usable to return.
		var typeErr *yaml.TypeError
		if strict || !errors.As(err, &typeErr) {
			return nil, "", nil, decodeError(name, err)
		}
	}
	box.srcName = name

	if strict {
		if err := checkSingleDocument(name, dec); err != nil {
			return nil, "", nil, err
		}
	}

	return box, absDir, data, nil
}

// checkBoxfileVersion enforces the required, supported version: field, reading
// it from the permissively-decoded document so the answer does not depend on
// the rest of the file parsing.
func checkBoxfileVersion(name string, raw map[string]any) error {
	rawVersion, hasVersion := raw["version"]
	if !hasVersion {
		return config.CheckVersion(0, CurrentBoxfileVersion, name)
	}
	version, ok := rawVersion.(int)
	if !ok {
		return fmt.Errorf("%s: version field must be an integer, got %T", name, rawVersion)
	}
	return config.CheckVersion(version, CurrentBoxfileVersion, name)
}

// checkSingleDocument rejects a file whose second document carries content,
// which the decoder would otherwise ignore silently.
//
// It inspects a yaml.Node rather than checking for io.EOF: a bare trailing
// "---" (or one followed only by comments) is still a document as far as the
// parser is concerned — it decodes without error into a document node whose
// single child is null — so an EOF check would reject a file that is not
// actually hiding anything.
func checkSingleDocument(name string, dec *yaml.Decoder) error {
	var next yaml.Node
	err := dec.Decode(&next)
	switch {
	case errors.Is(err, io.EOF):
		return nil
	case err != nil:
		return fmt.Errorf("failed to parse %s: %w", name, err)
	case isEmptyNode(&next):
		return nil // empty trailing document, nothing is being dropped
	default:
		return fmt.Errorf("%s must contain a single YAML document", name)
	}
}

// isEmptyNode reports whether a decoded document carries no content, unwrapping
// the document node the decoder hands back.
func isEmptyNode(n *yaml.Node) bool {
	if n.Kind == yaml.DocumentNode {
		if len(n.Content) == 0 {
			return true
		}
		n = n.Content[0]
	}
	return n.Kind == 0 || n.Tag == "!!null"
}

// ApplySuffix appends suffix to the instance name, joined with a hyphen, so the
// same abox.yaml can back several independent instances (e.g. name "my-agent"
// with suffix "1" becomes "my-agent-1"). An empty suffix is a no-op. Call before
// Validate so the resulting name is checked.
func (b *Boxfile) ApplySuffix(suffix string) {
	if suffix != "" {
		b.Name += "-" + suffix
	}
}

// Validate checks that required fields are present and paths exist.
func (b *Boxfile) Validate(baseDir string) error {
	if err := b.validateNameAndUser(); err != nil {
		return err
	}
	if err := b.validateResources(); err != nil {
		return err
	}
	if err := b.validateProvisionScripts(baseDir); err != nil {
		return err
	}
	if err := b.validateOverlay(baseDir); err != nil {
		return err
	}
	if err := b.validateMonitor(baseDir); err != nil {
		return err
	}
	if err := b.validateOverrides(baseDir); err != nil {
		return err
	}
	if b.HTTP.MaxConnections != nil && *b.HTTP.MaxConnections < 1 {
		return fmt.Errorf("invalid http.max_connections in %s: must be >= 1 (got %d)", b.fileName(), *b.HTTP.MaxConnections)
	}
	// Validate the SSRF allow-list with the same checker the filters use at
	// runtime, so a bad CIDR (or a default route that would disable protection)
	// is caught here rather than only when the daemon starts.
	if _, err := filterbase.NewTargetChecker(b.HTTP.AllowPrivateTargets); err != nil {
		return fmt.Errorf("invalid http.allow_private_targets in %s: %w", b.fileName(), err)
	}
	if err := config.ValidateSecretInjections(b.HTTP.SecretInjections); err != nil {
		return fmt.Errorf("invalid http.secret_injections in %s: %w", b.fileName(), err)
	}
	if err := config.ValidateMITMExceptions(b.HTTP.MITMExceptions, b.HTTP.SecretInjections); err != nil {
		return fmt.Errorf("invalid http.mitm_exceptions in %s: %w", b.fileName(), err)
	}
	return b.validateDNS()
}

func (b *Boxfile) validateNameAndUser() error {
	if b.Name == "" {
		return fmt.Errorf("name is required in %s", b.fileName())
	}
	if err := validation.ValidateInstanceName(b.Name); err != nil {
		return fmt.Errorf("invalid name in %s: %w", b.fileName(), err)
	}
	if b.User != "" {
		if err := validation.ValidateSSHUser(b.User); err != nil {
			return fmt.Errorf("invalid user in %s: %w", b.fileName(), err)
		}
	}
	return nil
}

func (b *Boxfile) validateResources() error {
	if err := validation.ValidateResourceLimits(b.CPUs, b.Memory); err != nil {
		return fmt.Errorf("invalid resource limits in %s: %w", b.fileName(), err)
	}
	if b.Disk != "" {
		if err := validation.ValidateDiskSize(b.Disk); err != nil {
			return fmt.Errorf("invalid disk size in %s: %w", b.fileName(), err)
		}
	}
	return nil
}

func (b *Boxfile) validateProvisionScripts(baseDir string) error {
	for _, script := range b.Provision {
		scriptPath, err := resolvePath(baseDir, script)
		if err != nil {
			return fmt.Errorf("provision script %q: %w", script, err)
		}
		if _, err := os.Stat(scriptPath); err != nil {
			if os.IsNotExist(err) {
				return fmt.Errorf("provision script not found: %s", scriptPath)
			}
			return fmt.Errorf("provision script %q: %w", script, err)
		}
	}
	return nil
}

func (b *Boxfile) validateOverlay(baseDir string) error {
	if b.Overlay == "" {
		return nil
	}
	overlayPath, err := resolvePath(baseDir, b.Overlay)
	if err != nil {
		return fmt.Errorf("overlay %q: %w", b.Overlay, err)
	}
	info, err := os.Stat(overlayPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("overlay directory not found: %s", overlayPath)
		}
		return fmt.Errorf("overlay %q: %w", b.Overlay, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("overlay path is not a directory: %s", overlayPath)
	}
	return nil
}

func (b *Boxfile) validateMonitor(baseDir string) error {
	if len(b.Monitor.Kprobes) > 0 && len(b.Monitor.Policies) > 0 {
		return fmt.Errorf("monitor.kprobes and monitor.policies are mutually exclusive in %s", b.fileName())
	}
	for _, name := range b.Monitor.Kprobes {
		if !policy.ValidKprobe(name) {
			return fmt.Errorf("unknown monitor kprobe %q in %s; valid kprobes: %v", name, b.fileName(), policy.AllKprobeNames())
		}
	}
	for _, p := range b.Monitor.Policies {
		policyPath, err := resolvePath(baseDir, p)
		if err != nil {
			return fmt.Errorf("monitor policy %q: %w", p, err)
		}
		if _, err := os.Stat(policyPath); err != nil {
			if os.IsNotExist(err) {
				return fmt.Errorf("monitor policy file not found: %s", policyPath)
			}
			return fmt.Errorf("monitor policy %q: %w", p, err)
		}
	}
	return nil
}

// validateOverrides checks that override file paths exist and are readable.
// Content validation (e.g., template syntax) is deferred to the backend layer
// which has the knowledge to validate its own override formats.
func (b *Boxfile) validateOverrides(baseDir string) error {
	for backend, overrides := range b.Overrides {
		for key, path := range overrides {
			if path == "" {
				continue
			}
			qualifiedKey := backend + "." + key
			resolved, err := resolvePath(baseDir, path)
			if err != nil {
				return fmt.Errorf("overrides.%s %q: %w", qualifiedKey, path, err)
			}
			if _, err := os.Stat(resolved); err != nil {
				if os.IsNotExist(err) {
					return fmt.Errorf("overrides.%s not found: %s", qualifiedKey, resolved)
				}
				return fmt.Errorf("overrides.%s: %w", qualifiedKey, err)
			}
		}
	}
	return nil
}

func (b *Boxfile) validateDNS() error {
	if b.DNS.Upstream != "" {
		normalized, err := validation.NormalizeUpstreamDNS(b.DNS.Upstream)
		if err != nil {
			return fmt.Errorf("invalid dns.upstream in %s: %w", b.fileName(), err)
		}
		b.DNS.Upstream = normalized
	}
	return nil
}

// resolvePath resolves a path relative to the base directory.
// Absolute paths are returned as-is. Relative paths are joined with baseDir
// and checked for path traversal (escaping baseDir).
func resolvePath(baseDir, path string) (string, error) {
	if filepath.IsAbs(path) {
		return path, nil
	}
	resolved := filepath.Clean(filepath.Join(baseDir, path))
	cleanBase := filepath.Clean(baseDir)
	if resolved != cleanBase && !strings.HasPrefix(resolved, cleanBase+string(filepath.Separator)) {
		return "", fmt.Errorf("path %q escapes base directory %q", path, baseDir)
	}
	return resolved, nil
}

// ResolveProvisionPaths returns absolute paths for all provision scripts.
func (b *Boxfile) ResolveProvisionPaths(baseDir string) ([]string, error) {
	paths := make([]string, len(b.Provision))
	for i, script := range b.Provision {
		p, err := resolvePath(baseDir, script)
		if err != nil {
			return nil, fmt.Errorf("provision script %q: %w", script, err)
		}
		paths[i] = p
	}
	return paths, nil
}

// ResolvePolicyPaths returns absolute paths for all monitor policy files.
func (b *Boxfile) ResolvePolicyPaths(baseDir string) ([]string, error) {
	paths := make([]string, len(b.Monitor.Policies))
	for i, p := range b.Monitor.Policies {
		resolved, err := resolvePath(baseDir, p)
		if err != nil {
			return nil, fmt.Errorf("monitor policy %q: %w", p, err)
		}
		paths[i] = resolved
	}
	return paths, nil
}

// ResolveOverridePath returns the absolute path for an override value.
// Returns empty string if the override is not configured.
func (b *Boxfile) ResolveOverridePath(backend, key, baseDir string) (string, error) {
	path := b.Overrides[backend][key]
	if path == "" {
		return "", nil
	}
	return resolvePath(baseDir, path)
}

// LoadOverrideContent reads an override file and returns its content.
// Returns empty string if the override is not configured.
func (b *Boxfile) LoadOverrideContent(backend, key, baseDir string) (string, error) {
	path := b.Overrides[backend][key]
	if path == "" {
		return "", nil
	}
	resolved, err := b.ResolveOverridePath(backend, key, baseDir)
	if err != nil {
		return "", err
	}
	content, err := os.ReadFile(resolved)
	if err != nil {
		return "", fmt.Errorf("failed to read override %s.%s: %w", backend, key, err)
	}
	return string(content), nil
}

// ResolveOverlayPath returns the absolute path for the overlay directory.
func (b *Boxfile) ResolveOverlayPath(baseDir string) (string, error) {
	if b.Overlay == "" {
		return "", nil
	}
	return resolvePath(baseDir, b.Overlay)
}
